<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authorization\**" />
    <Compile Remove="Persistence\Migrations\**" />
    <Compile Remove="Persistence\Generated\**" />
    <EmbeddedResource Remove="Authorization\**" />
    <EmbeddedResource Remove="Persistence\Migrations\**" />
    <None Remove="Authorization\**" />
    <None Remove="Persistence\Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Persistence\Generated\Entities\AccAccountingPeriod.cs" />
    <Compile Include="Persistence\Generated\Entities\AccAccountingPolicy.cs" />
    <Compile Include="Persistence\Generated\Entities\AccAccountType.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccount.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountPreset.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountPresetAccount.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountPresetAccountSubkonto.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountPresetAccountTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountPresetTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\AccChartAccountSubkonto.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountRole.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountRoleTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountSetting.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountType.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountTypeRole.cs" />
    <Compile Include="Persistence\Generated\Entities\AccDocumentAccountTypeTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\AccPostingBatch.cs" />
    <Compile Include="Persistence\Generated\Entities\AccRegEntry.cs" />
    <Compile Include="Persistence\Generated\Entities\AccRegEntrySubkonto.cs" />
    <Compile Include="Persistence\Generated\Entities\AccSubkontoType.cs" />
    <Compile Include="Persistence\Generated\Entities\AccSubkontoTypeTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\AppDbContext.cs" />
    <Compile Include="Persistence\Generated\Entities\BankOperation.cs" />
    <Compile Include="Persistence\Generated\Entities\CashBox.cs" />
    <Compile Include="Persistence\Generated\Entities\CashOperation.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnBank.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnContract.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnContractType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCostingMethod.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCounterpartyType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCurrency.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCurrencyRate.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCurrencyRevaluation.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnCurrencyRevaluationLine.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnDistrict.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnDocumentSequence.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnDocumentStatus.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnDocumentType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnFaAssetStatus.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnFaDepreciationMethod.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnFaGroup.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnFaOkof.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnInventoryAdjustmentType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnLanguage.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnNotificationType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnOperationType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnPaymentType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnPriceRoundingMethod.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnPricingCondition.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnPricingMethod.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnProductPriceType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnProductTableStatus.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnProductType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnProductTypeTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnRegion.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnState.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnTaxType.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnTranslation.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnUnit.cs" />
    <Compile Include="Persistence\Generated\Entities\CmnVatRate.cs" />
    <Compile Include="Persistence\Generated\Entities\CounterpartyBankAccount.cs" />
    <Compile Include="Persistence\Generated\Entities\CounterpartyCard.cs" />
    <Compile Include="Persistence\Generated\Entities\CounterpartyContact.cs" />
    <Compile Include="Persistence\Generated\Entities\CounterpartyRegBalance.cs" />
    <Compile Include="Persistence\Generated\Entities\FaAsset.cs" />
    <Compile Include="Persistence\Generated\Entities\FaDepreciationRun.cs" />
    <Compile Include="Persistence\Generated\Entities\FaDepreciationRunLine.cs" />
    <Compile Include="Persistence\Generated\Entities\FaDisposalDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\FaDisposalDocLine.cs" />
    <Compile Include="Persistence\Generated\Entities\FaMovementDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\FaMovementDocLine.cs" />
    <Compile Include="Persistence\Generated\Entities\FaReceiptDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\FaReceiptDocAsset.cs" />
    <Compile Include="Persistence\Generated\Entities\FaReceiptDocLine.cs" />
    <Compile Include="Persistence\Generated\Entities\FaRevaluationDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\FaRevaluationDocLine.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryAdjustmentDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryAdjustmentDocTable.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryAdjustmentLine.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryCountDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryCountDocTable.cs" />
    <Compile Include="Persistence\Generated\Entities\InvInventoryCountLine.cs" />
    <Compile Include="Persistence\Generated\Entities\InvProduct.cs" />
    <Compile Include="Persistence\Generated\Entities\InvProductGroup.cs" />
    <Compile Include="Persistence\Generated\Entities\InvProductPrice.cs" />
    <Compile Include="Persistence\Generated\Entities\InvProductTable.cs" />
    <Compile Include="Persistence\Generated\Entities\InvRegBalance.cs" />
    <Compile Include="Persistence\Generated\Entities\InvTransferDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\InvTransferDocTable.cs" />
    <Compile Include="Persistence\Generated\Entities\InvTransferLine.cs" />
    <Compile Include="Persistence\Generated\Entities\InvWarehouse.cs" />
    <Compile Include="Persistence\Generated\Entities\InvWarehouseProduct.cs" />
    <Compile Include="Persistence\Generated\Entities\MoneyRegBalance.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgBankAccount.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgBranch.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgClaimRequest.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgDefault.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgDepartment.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgOrganization.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgOrganizationConfig.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgPosition.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgSetupState.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgTaxSetting.cs" />
    <Compile Include="Persistence\Generated\Entities\OrgUserInvitation.cs" />
    <Compile Include="Persistence\Generated\Entities\PlatformTenant.cs" />
    <Compile Include="Persistence\Generated\Entities\PurDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\PurDocProduct.cs" />
    <Compile Include="Persistence\Generated\Entities\PurDocTable.cs" />
    <Compile Include="Persistence\Generated\Entities\SaleCondition.cs" />
    <Compile Include="Persistence\Generated\Entities\SaleDoc.cs" />
    <Compile Include="Persistence\Generated\Entities\SaleDocProduct.cs" />
    <Compile Include="Persistence\Generated\Entities\SaleDocTable.cs" />
    <Compile Include="Persistence\Generated\Entities\SysAuditLog.cs" />
    <Compile Include="Persistence\Generated\Entities\SysEmailVerificationToken.cs" />
    <Compile Include="Persistence\Generated\Entities\SysModule.cs" />
    <Compile Include="Persistence\Generated\Entities\SysModuleSubGroup.cs" />
    <Compile Include="Persistence\Generated\Entities\SysNotification.cs" />
    <Compile Include="Persistence\Generated\Entities\SysNotificationDelivery.cs" />
    <Compile Include="Persistence\Generated\Entities\SysNotificationRead.cs" />
    <Compile Include="Persistence\Generated\Entities\SysPasswordResetToken.cs" />
    <Compile Include="Persistence\Generated\Entities\SysRefreshToken.cs" />
    <Compile Include="Persistence\Generated\Entities\SysRole.cs" />
    <Compile Include="Persistence\Generated\Entities\SysRoleModule.cs" />
    <Compile Include="Persistence\Generated\Entities\SysSetting.cs" />
    <Compile Include="Persistence\Generated\Entities\SysUser.cs" />
    <Compile Include="Persistence\Generated\Entities\SysUserOrganization.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.70.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.70.0.3834" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.8" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
    <PackageReference Include="Quartz" Version="3.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />

    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
