create table marking_transfer
(
    id                          bigint generated by default as identity not null,
    organization_id             integer not null,
    seller_counterparty_id      integer not null,
    buyer_counterparty_id       integer not null,
    transfer_date               timestamp without time zone not null,
    document_id                 character varying(100),
    status                      character varying(50) not null,
    external_document_reference character varying(200),
    created_date                timestamp without time zone default now() not null,
    updated_date                timestamp without time zone,
    constraint marking_transfer_pkey primary key (id),
    constraint marking_transfer_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_transfer_seller_counterparty_id_fkey foreign key (seller_counterparty_id) references counterparty_card(id),
    constraint marking_transfer_buyer_counterparty_id_fkey foreign key (buyer_counterparty_id) references counterparty_card(id)
);

create index idx_marking_transfer_organization_id on marking_transfer using btree (organization_id);
create index idx_marking_transfer_seller_counterparty_id on marking_transfer using btree (seller_counterparty_id);
create index idx_marking_transfer_buyer_counterparty_id on marking_transfer using btree (buyer_counterparty_id);
create index idx_marking_transfer_transfer_date on marking_transfer using btree (transfer_date);
create index idx_marking_transfer_status on marking_transfer using btree (organization_id, status);
create index idx_marking_transfer_document_id on marking_transfer using btree (document_id) where document_id is not null;

