create table int_provider_credential
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    provider character varying(32) not null,
    external_tin character varying(20) not null,
    entity_id character varying(200),
    credential_kind character varying(32) not null,
    encrypted_secret_reference character varying(1000) not null,
    key_version integer not null,
    status character varying(16) not null,
    valid_from_utc timestamp without time zone default now() not null,
    expires_at_utc timestamp without time zone,
    revoked_at_utc timestamp without time zone,
    created_by_user_id integer,
    created_at_utc timestamp without time zone default now() not null,
    updated_at_utc timestamp without time zone default now() not null,
    constraint int_provider_credential_pkey primary key (id),
    constraint int_provider_credential_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint int_provider_credential_created_by_user_id_fkey
        foreign key (created_by_user_id) references sys_user(id),
    constraint int_provider_credential_secret_reference_check
        check (btrim(encrypted_secret_reference) <> ''),
    constraint int_provider_credential_provider_check
        check (provider in ('Didox', 'EDocs', 'AslBelgi')),
    constraint int_provider_credential_external_tin_check
        check (external_tin ~ '^[0-9]+$'),
    constraint int_provider_credential_entity_id_check
        check (entity_id is null or btrim(entity_id) <> ''),
    constraint int_provider_credential_kind_check
        check (credential_kind in ('PartnerToken', 'CompanyToken', 'TechnicalLogin', 'TechnicalPassword', 'ApiKey', 'EImzoCertificate', 'Other')),
    constraint int_provider_credential_key_version_check
        check (key_version > 0),
    constraint int_provider_credential_status_check
        check (status in ('Active', 'Rotating', 'Revoked', 'Expired')),
    constraint int_provider_credential_revoked_at_check
        check (status <> 'Revoked' or revoked_at_utc is not null),
    constraint int_provider_credential_expiry_check
        check (expires_at_utc is null or expires_at_utc > valid_from_utc)
);

create unique index ux_int_provider_credential_scope
    on int_provider_credential
    using btree
    (organization_id, provider, external_tin, coalesce(entity_id, ''), credential_kind);

create index idx_int_provider_credential_organization_id
    on int_provider_credential using btree (organization_id);

create index idx_int_provider_credential_provider
    on int_provider_credential using btree (provider);

create index idx_int_provider_credential_external_tin
    on int_provider_credential using btree (external_tin);

create index idx_int_provider_credential_status
    on int_provider_credential using btree (status);
