create table int_provider_session
(
    id bigint generated by default as identity not null,
    provider_credential_id bigint not null,
    organization_id integer not null,
    provider character varying(32) not null,
    external_tin character varying(20) not null,
    entity_id character varying(200),
    encrypted_access_token_reference character varying(1000) not null,
    encrypted_refresh_token_reference character varying(1000),
    token_fingerprint character varying(128) not null,
    access_expires_at_utc timestamp without time zone,
    refresh_expires_at_utc timestamp without time zone,
    credential_version integer not null,
    status character varying(16) not null,
    last_401_at_utc timestamp without time zone,
    revoked_at_utc timestamp without time zone,
    created_at_utc timestamp without time zone default now() not null,
    updated_at_utc timestamp without time zone default now() not null,
    constraint int_provider_session_pkey primary key (id),
    constraint int_provider_session_provider_credential_id_fkey
        foreign key (provider_credential_id) references int_provider_credential(id),
    constraint int_provider_session_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint int_provider_session_access_reference_check
        check (btrim(encrypted_access_token_reference) <> ''),
    constraint int_provider_session_token_fingerprint_check
        check (btrim(token_fingerprint) <> ''),
    constraint int_provider_session_provider_check
        check (provider in ('Didox', 'EDocs', 'AslBelgi')),
    constraint int_provider_session_external_tin_check
        check (external_tin ~ '^[0-9]+$'),
    constraint int_provider_session_entity_id_check
        check (entity_id is null or btrim(entity_id) <> ''),
    constraint int_provider_session_credential_version_check
        check (credential_version > 0),
    constraint int_provider_session_status_check
        check (status in ('Active', 'Expired', 'Revoked')),
    constraint int_provider_session_revoked_at_check
        check (status <> 'Revoked' or revoked_at_utc is not null)
);

create unique index ux_int_provider_session_scope
    on int_provider_session
    using btree
    (organization_id, provider, external_tin, coalesce(entity_id, ''));

create index idx_int_provider_session_organization_id
    on int_provider_session using btree (organization_id);

create index idx_int_provider_session_provider_credential_id
    on int_provider_session using btree (provider_credential_id);

create index idx_int_provider_session_provider
    on int_provider_session using btree (provider);

create index idx_int_provider_session_external_tin
    on int_provider_session using btree (external_tin);

create index idx_int_provider_session_status
    on int_provider_session using btree (status);
