create table marking_transfer_code
(
    id                  bigint generated by default as identity not null,
    organization_id     integer not null,
    marking_transfer_id  bigint not null,
    marking_code        character varying(1000) not null,
    gtin                character varying(14),
    quantity            numeric(18,3) not null,
    created_date        timestamp without time zone default now() not null,
    updated_date        timestamp without time zone,
    constraint marking_transfer_code_pkey primary key (id),
    constraint marking_transfer_code_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_transfer_code_marking_transfer_id_fkey foreign key (marking_transfer_id) references marking_transfer(id) on delete cascade
);

create index idx_marking_transfer_code_organization_id on marking_transfer_code using btree (organization_id);
create index idx_marking_transfer_code_marking_transfer_id on marking_transfer_code using btree (marking_transfer_id);
create index idx_marking_transfer_code_gtin on marking_transfer_code using btree (gtin) where gtin is not null;
create unique index uidx_marking_transfer_code_transfer_code on marking_transfer_code using btree (marking_transfer_id, marking_code);

