create table int_provider_operation
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    provider character varying(32) not null,
    operation character varying(100) not null,
    client_request_id character varying(200) not null,
    request_hash character varying(128) not null,
    external_operation_id character varying(200),
    state character varying(20) not null,
    reconcile_required boolean default false not null,
    last_external_status character varying(100),
    last_error_code character varying(100),
    created_at_utc timestamp without time zone default now() not null,
    updated_at_utc timestamp without time zone default now() not null,
    completed_at_utc timestamp without time zone,
    constraint int_provider_operation_pkey primary key (id),
    constraint int_provider_operation_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint int_provider_operation_operation_check
        check (btrim(operation) <> ''),
    constraint int_provider_operation_client_request_id_check
        check (btrim(client_request_id) <> ''),
    constraint int_provider_operation_request_hash_check
        check (btrim(request_hash) <> ''),
    constraint int_provider_operation_provider_check
        check (provider in ('Didox', 'EDocs', 'AslBelgi')),
    constraint int_provider_operation_state_check
        check (state in ('Pending', 'Sent', 'Confirmed', 'Failed', 'Unknown', 'ReconcileRequired')),
    constraint int_provider_operation_completed_at_check
        check (completed_at_utc is null or completed_at_utc >= created_at_utc)
);

create unique index ux_int_provider_operation_idempotency
    on int_provider_operation
    using btree
    (organization_id, provider, operation, client_request_id);

create index idx_int_provider_operation_organization_id
    on int_provider_operation using btree (organization_id);

create index idx_int_provider_operation_provider
    on int_provider_operation using btree (provider);

create index idx_int_provider_operation_state
    on int_provider_operation using btree (state);

create index idx_int_provider_operation_external_operation_id
    on int_provider_operation using btree (external_operation_id);
