create table idempotency_record
(
    id                  bigint generated by default as identity not null,
    organization_id     integer not null,
    idempotency_key     character varying(200) not null,
    operation_type      character varying(100) not null,
    request_hash        character varying(128),
    request_reference   character varying(200),
    result_document_id  character varying(100),
    status              character varying(50) not null,
    created_date        timestamp without time zone default now() not null,
    updated_date        timestamp without time zone,
    constraint idempotency_record_pkey primary key (id),
    constraint idempotency_record_organization_id_fkey foreign key (organization_id) references org_organization(id)
);

create index idx_idempotency_record_organization_id on idempotency_record using btree (organization_id);
create index idx_idempotency_record_status on idempotency_record using btree (organization_id, status);
create unique index uidx_idempotency_record_org_key on idempotency_record using btree (organization_id, idempotency_key);

