create table marking_business_place
(
    id               integer generated by default as identity not null,
    organization_id  integer not null,
    external_id      character varying(50) not null,
    name             character varying(200) not null,
    address          character varying(500),
    is_manufacturing boolean not null default false,
    is_storage       boolean not null default false,
    is_sale          boolean not null default false,
    is_active        boolean not null default true,
    created_date     timestamp without time zone default now() not null,
    updated_date     timestamp without time zone,
    constraint marking_business_place_pkey primary key (id),
    constraint marking_business_place_organization_id_fkey foreign key (organization_id) references org_organization(id)
);

create index idx_marking_business_place_organization_id on marking_business_place using btree (organization_id);
create unique index ux_marking_business_place_org_external_id on marking_business_place using btree (organization_id, external_id);
