create table int_eimzo_challenge
(
    id bigint generated by default as identity not null,
    challenge_id character varying(128) not null,
    organization_id integer not null,
    provider character varying(32) not null,
    external_tin character varying(20) not null,
    entity_id character varying(200) not null,
    auth_id_hash character varying(128),
    payload_hash character varying(128),
    sign_mode character varying(16),
    expires_at_utc timestamp without time zone not null,
    consumed_at_utc timestamp without time zone,
    state character varying(16) not null,
    created_at_utc timestamp without time zone default now() not null,
    constraint int_eimzo_challenge_pkey primary key (id),
    constraint int_eimzo_challenge_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint int_eimzo_challenge_challenge_id_check
        check (btrim(challenge_id) <> ''),
    constraint int_eimzo_challenge_provider_check
        check (provider in ('Didox', 'EDocs', 'AslBelgi')),
    constraint int_eimzo_challenge_external_tin_check
        check (external_tin ~ '^[0-9]+$'),
    constraint int_eimzo_challenge_entity_id_check
        check (btrim(entity_id) <> ''),
    constraint int_eimzo_challenge_hash_check
        check ((auth_id_hash is not null) <> (payload_hash is not null)),
    constraint int_eimzo_challenge_state_check
        check (state in ('Pending', 'Consumed', 'Expired')),
    constraint int_eimzo_challenge_consumed_at_check
        check (state <> 'Consumed' or consumed_at_utc is not null),
    constraint int_eimzo_challenge_sign_mode_check
        check (sign_mode is null or sign_mode in ('Attached', 'Detached')),
    constraint int_eimzo_challenge_expiry_check
        check (expires_at_utc > created_at_utc)
);

create unique index ux_int_eimzo_challenge_challenge_id
    on int_eimzo_challenge using btree (challenge_id);

create index idx_int_eimzo_challenge_scope_state
    on int_eimzo_challenge using btree
    (organization_id, provider, external_tin, entity_id, state);

create index idx_int_eimzo_challenge_expiry_state
    on int_eimzo_challenge using btree (expires_at_utc, state);
