create table marking_order
(
    id                 bigint generated by default as identity not null,
    organization_id    integer not null,
    business_place_id  integer not null,
    product_id         integer not null,
    gtin               character varying(14) not null,
    quantity           integer not null,
    crpt_order_id      character varying(100),
    status             character varying(30) not null,
    created_at         timestamp without time zone default now() not null,
    constraint marking_order_pkey primary key (id),
    constraint marking_order_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_order_business_place_id_fkey foreign key (business_place_id) references marking_business_place(id),
    constraint marking_order_product_id_fkey foreign key (product_id) references inv_product(id)
);

create index idx_marking_order_organization_id on marking_order using btree (organization_id);
create index idx_marking_order_business_place_id on marking_order using btree (business_place_id);
create index idx_marking_order_product_id on marking_order using btree (product_id);
create index idx_marking_order_status on marking_order using btree (organization_id, status);
create unique index ux_marking_order_crpt_order_id on marking_order using btree (crpt_order_id) where crpt_order_id is not null;
