create table marking_utilization
(
    id                 bigint generated by default as identity not null,
    organization_id    integer not null,
    business_place_id  integer not null,
    crpt_document_id   character varying(100),
    production_date    date not null,
    expiration_date    date,
    status             character varying(30) not null,
    created_at         timestamp without time zone default now() not null,
    constraint marking_utilization_pkey primary key (id),
    constraint marking_utilization_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_utilization_business_place_id_fkey foreign key (business_place_id) references marking_business_place(id)
);

create index idx_marking_utilization_organization_id on marking_utilization using btree (organization_id);
create index idx_marking_utilization_business_place_id on marking_utilization using btree (business_place_id);
create index idx_marking_utilization_status on marking_utilization using btree (organization_id, status);
create unique index ux_marking_utilization_crpt_document_id on marking_utilization using btree (crpt_document_id) where crpt_document_id is not null;
