create table marking_code
(
    id                     bigint generated by default as identity not null,
    organization_id        integer not null,
    product_id             integer not null,
    gtin                   character varying(14) not null,
    serial_number          character varying(20) not null,
    check_key              character varying(4) not null,
    check_code             character varying(44) not null,
    status                 character varying(30) not null,
    owner_counterparty_id  integer,
    warehouse_id           integer,
    parent_marking_code_id bigint,
    order_id               bigint,
    utilization_id         bigint,
    created_at             timestamp without time zone default now() not null,
    updated_at             timestamp without time zone,
    constraint ck_marking_code_status check (status in ('in_circulation', 'withdrawn', 'utilized', 'sold')),
    constraint marking_code_pkey primary key (id),
    constraint marking_code_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_code_product_id_fkey foreign key (product_id) references inv_product(id),
    constraint marking_code_owner_counterparty_id_fkey foreign key (owner_counterparty_id) references counterparty_card(id),
    constraint marking_code_warehouse_id_fkey foreign key (warehouse_id) references inv_warehouse(id),
    constraint marking_code_parent_marking_code_id_fkey foreign key (parent_marking_code_id) references marking_code(id),
    constraint marking_code_order_id_fkey foreign key (order_id) references marking_order(id),
    constraint marking_code_utilization_id_fkey foreign key (utilization_id) references marking_utilization(id)
);

create index idx_marking_code_organization_id on marking_code using btree (organization_id);
create index idx_marking_code_product_id on marking_code using btree (product_id);
create index idx_marking_code_status on marking_code using btree (organization_id, status);
create index idx_marking_code_owner_counterparty_id on marking_code using btree (owner_counterparty_id);
create index idx_marking_code_warehouse_id on marking_code using btree (warehouse_id);
create index idx_marking_code_parent_marking_code_id on marking_code using btree (parent_marking_code_id);
create index idx_marking_code_order_id on marking_code using btree (order_id);
create index idx_marking_code_utilization_id on marking_code using btree (utilization_id);
create unique index ux_marking_code_org_gtin_serial on marking_code using btree (organization_id, gtin, serial_number);
