create table marking_aggregation
(
    id                     bigint generated by default as identity not null,
    organization_id        integer not null,
    business_place_id      integer not null,
    parent_marking_code_id bigint not null,
    packing_date           date not null,
    crpt_document_id       character varying(100),
    planned_capacity       integer not null,
    actual_capacity        integer not null,
    status                 character varying(30) not null,
    created_at             timestamp without time zone default now() not null,
    constraint marking_aggregation_pkey primary key (id),
    constraint marking_aggregation_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint marking_aggregation_business_place_id_fkey foreign key (business_place_id) references marking_business_place(id),
    constraint marking_aggregation_parent_marking_code_id_fkey foreign key (parent_marking_code_id) references marking_code(id)
);

create index idx_marking_aggregation_organization_id on marking_aggregation using btree (organization_id);
create index idx_marking_aggregation_business_place_id on marking_aggregation using btree (business_place_id);
create index idx_marking_aggregation_parent_marking_code_id on marking_aggregation using btree (parent_marking_code_id);
create index idx_marking_aggregation_status on marking_aggregation using btree (organization_id, status);
create unique index ux_marking_aggregation_crpt_document_id on marking_aggregation using btree (crpt_document_id) where crpt_document_id is not null;
