create table marking_didox_document
(
    id                      bigint generated by default as identity not null,
    organization_id         integer not null,
    operation_type          character varying(30) not null,
    internal_document_type  character varying(50) not null,
    internal_document_id    bigint not null,
    provider_document_id    character varying(100),
    status                  character varying(30) not null,
    error_message           text,
    created_at              timestamp without time zone default now() not null,
    updated_at              timestamp without time zone,
    constraint marking_didox_document_pkey primary key (id),
    constraint marking_didox_document_organization_id_fkey foreign key (organization_id) references org_organization(id)
);

create index idx_marking_didox_document_organization_id on marking_didox_document using btree (organization_id);
create index idx_marking_didox_document_internal_document on marking_didox_document using btree (internal_document_type, internal_document_id);
create index idx_marking_didox_document_status on marking_didox_document using btree (organization_id, status);
create unique index ux_marking_didox_document_provider_document_id on marking_didox_document using btree (provider_document_id) where provider_document_id is not null;
