create table integration_credential
(
    id              bigint generated by default as identity not null,
    organization_id integer not null,
    provider        character varying(20) not null,
    tin             character varying(20),
    api_key         text,
    login           character varying(100),
    password        text,
    client_id       character varying(100),
    client_secret   text,
    partner_id      character varying(100),
    valid_until     timestamptz,
    is_active       boolean not null default true,
    created_date    timestamp without time zone default now() not null,
    updated_date    timestamp without time zone,
    constraint integration_credential_pkey primary key (id),
    constraint integration_credential_organization_id_fkey foreign key (organization_id) references org_organization(id)
);

create index idx_integration_credential_organization_id on integration_credential using btree (organization_id);
create unique index ux_integration_credential_organization_id_provider on integration_credential using btree (organization_id, provider);
