create table edo_document
(
    id                       bigint generated by default as identity not null,
    organization_id          integer not null,
    provider                 character varying(20) not null,
    direction                character varying(10) not null,
    internal_document_type   character varying(50) not null,
    internal_document_id     bigint not null,
    legacy_document_id       bigint,
    provider_document_id     character varying(100),
    document_type            character varying(50) not null,
    document_number          character varying(100),
    document_date            date,
    status                   character varying(40) not null,
    provider_status_code     character varying(100),
    error_message            text,
    reject_reason            character varying(2000),
    operation_type           character varying(100) not null,
    idempotency_key          character varying(200),
    created_at               timestamp without time zone default now() not null,
    updated_at               timestamp without time zone,
    constraint edo_document_pkey primary key (id),
    constraint edo_document_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint ck_edo_document_provider
        check (provider in ('DIDOX', 'FAKTURA', 'EDOCS')),
    constraint ck_edo_document_direction
        check (direction in ('OUTBOX', 'INBOX'))
);

create unique index ux_edo_document_organization_provider_document
    on edo_document using btree (organization_id, provider, provider_document_id)
    where provider_document_id is not null;

create unique index ux_edo_document_organization_provider_operation_key
    on edo_document using btree (organization_id, provider, operation_type, idempotency_key)
    where idempotency_key is not null;

create index idx_edo_document_organization_status
    on edo_document using btree (organization_id, provider, direction, status);
