create table edo_import_job
(
    id                       bigint generated by default as identity not null,
    organization_id          integer not null,
    initiated_by_user_id     integer not null,
    date_from                date not null,
    date_to                  date not null,
    status                   character varying(40) not null,
    scan_started_at          timestamp without time zone,
    started_at               timestamp without time zone,
    completed_at             timestamp without time zone,
    cancel_requested_at      timestamp without time zone,
    lease_owner              character varying(200),
    lease_expires_at         timestamp without time zone,
    heartbeat_at             timestamp without time zone,
    safe_error_code          character varying(100),
    safe_error_message       character varying(1000),
    discovered_count         integer default 0 not null,
    ready_count              integer default 0 not null,
    mapping_required_count   integer default 0 not null,
    duplicate_count          integer default 0 not null,
    imported_count           integer default 0 not null,
    failed_count             integer default 0 not null,
    skipped_count            integer default 0 not null,
    created_date             timestamp without time zone default now() not null,
    updated_date             timestamp without time zone,
    constraint edo_import_job_pkey primary key (id),
    constraint ux_edo_import_job_id_organization unique (id, organization_id),
    constraint edo_import_job_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint edo_import_job_initiated_by_user_id_fkey
        foreign key (initiated_by_user_id) references sys_user(id),
    constraint ck_edo_import_job_date_range
        check (date_from <= date_to),
    constraint ck_edo_import_job_status
        check (status in ('QUEUED', 'SCANNING', 'WAITING_AUTH', 'PREFLIGHT_READY', 'IMPORTING', 'PARTIAL', 'COMPLETED', 'FAILED', 'CANCEL_REQUESTED', 'CANCELLED')),
    constraint ck_edo_import_job_counts
        check (discovered_count >= 0 and ready_count >= 0 and mapping_required_count >= 0 and duplicate_count >= 0 and imported_count >= 0 and failed_count >= 0 and skipped_count >= 0)
);

create unique index ux_edo_import_job_active_organization
    on edo_import_job using btree (organization_id)
    where status in ('QUEUED', 'SCANNING', 'WAITING_AUTH', 'PREFLIGHT_READY', 'IMPORTING', 'PARTIAL', 'CANCEL_REQUESTED');

create index idx_edo_import_job_status_lease
    on edo_import_job using btree (status, lease_expires_at);
