create table edo_import_job_provider
(
    id                    bigint generated by default as identity not null,
    job_id                bigint not null,
    provider_code         character varying(20) not null,
    status                character varying(40) not null,
    current_page          integer default 1 not null,
    page_size             integer default 20 not null,
    provider_total        integer,
    scanned_count         integer default 0 not null,
    last_successful_page  integer,
    last_attempt_at       timestamp without time zone,
    next_retry_at         timestamp without time zone,
    attempt_count         integer default 0 not null,
    scan_completed_at     timestamp without time zone,
    is_waiting_auth       boolean default false not null,
    safe_error_code       character varying(100),
    created_date          timestamp without time zone default now() not null,
    updated_date          timestamp without time zone,
    constraint edo_import_job_provider_pkey primary key (id),
    constraint ux_edo_import_job_provider_job_provider unique (job_id, provider_code),
    constraint edo_import_job_provider_job_id_fkey
        foreign key (job_id) references edo_import_job(id) on delete cascade,
    constraint ck_edo_import_job_provider_provider
        check (provider_code in ('EDOCS', 'DIDOX')),
    constraint ck_edo_import_job_provider_status
        check (status in ('QUEUED', 'SCANNING', 'WAITING_AUTH', 'PARTIAL', 'COMPLETED', 'FAILED', 'CANCELLED')),
    constraint ck_edo_import_job_provider_paging
        check (current_page >= 1 and page_size >= 1 and scanned_count >= 0 and attempt_count >= 0 and (provider_total is null or provider_total >= 0) and (last_successful_page is null or last_successful_page >= 1)),
    constraint ck_edo_import_job_provider_waiting_auth
        check (is_waiting_auth = (status = 'WAITING_AUTH'))
);

create index idx_edo_import_job_provider_status_retry
    on edo_import_job_provider using btree (status, next_retry_at);
