create table edo_import_candidate
(
    id                          bigint generated by default as identity not null,
    job_id                      bigint not null,
    organization_id             integer not null,
    provider_code               character varying(20) not null,
    provider_document_id        character varying(100) not null,
    edo_document_id             bigint,
    direction                   character varying(10),
    normalized_status           character varying(40),
    document_type               character varying(50),
    document_number             character varying(100),
    document_date               date,
    seller_tin                  character varying(20),
    buyer_tin                   character varying(20),
    seller_name                 character varying(500),
    provider_contract_number    character varying(100),
    provider_contract_date      date,
    net_amount                  numeric(24, 8),
    vat_amount                  numeric(24, 8),
    total_amount                numeric(24, 8),
    shared_document_identity    character varying(200),
    header_fingerprint          character varying(64),
    content_fingerprint         character varying(64),
    duplicate_state             character varying(30) default 'NONE' not null,
    existing_purchase_id        bigint,
    selected_counterparty_id    integer,
    selected_contract_id        bigint,
    selected_currency_id        smallint,
    selected_warehouse_id       integer,
    mapping_status              character varying(30) default 'UNRESOLVED' not null,
    status                      character varying(40) default 'DISCOVERED' not null,
    safe_error_code             character varying(100),
    attempt_count               integer default 0 not null,
    imported_purchase_id        bigint,
    created_date                timestamp without time zone default now() not null,
    updated_date                timestamp without time zone,
    constraint edo_import_candidate_pkey primary key (id),
    constraint ux_edo_import_candidate_job_provider_document
        unique (job_id, provider_code, provider_document_id),
    constraint edo_import_candidate_job_organization_fkey
        foreign key (job_id, organization_id) references edo_import_job(id, organization_id) on delete cascade,
    constraint edo_import_candidate_job_provider_fkey
        foreign key (job_id, provider_code) references edo_import_job_provider(job_id, provider_code),
    constraint edo_import_candidate_organization_id_fkey
        foreign key (organization_id) references org_organization(id),
    constraint edo_import_candidate_edo_document_id_fkey
        foreign key (edo_document_id) references edo_document(id) on delete set null,
    constraint edo_import_candidate_existing_purchase_id_fkey
        foreign key (existing_purchase_id) references pur_doc(id) on delete set null,
    constraint edo_import_candidate_imported_purchase_id_fkey
        foreign key (imported_purchase_id) references pur_doc(id) on delete set null,
    constraint edo_import_candidate_selected_counterparty_id_fkey
        foreign key (selected_counterparty_id) references counterparty_card(id) on delete set null,
    constraint edo_import_candidate_selected_contract_id_fkey
        foreign key (selected_contract_id) references cmn_contract(id) on delete set null,
    constraint edo_import_candidate_selected_currency_id_fkey
        foreign key (selected_currency_id) references cmn_currency(id) on delete set null,
    constraint edo_import_candidate_selected_warehouse_id_fkey
        foreign key (selected_warehouse_id) references inv_warehouse(id) on delete set null,
    constraint ck_edo_import_candidate_provider
        check (provider_code in ('EDOCS', 'DIDOX')),
    constraint ck_edo_import_candidate_direction
        check (direction is null or direction in ('INBOX', 'OUTBOX')),
    constraint ck_edo_import_candidate_status
        check (status in ('DISCOVERED', 'MAPPING_REQUIRED', 'READY', 'POSSIBLE_DUPLICATE', 'DUPLICATE', 'IMPORTING', 'IMPORTED', 'FAILED', 'SKIPPED')),
    constraint ck_edo_import_candidate_mapping_status
        check (mapping_status in ('UNRESOLVED', 'PARTIAL', 'RESOLVED')),
    constraint ck_edo_import_candidate_duplicate_state
        check (duplicate_state in ('NONE', 'POSSIBLE', 'CONFIRMED')),
    constraint ck_edo_import_candidate_attempt_count
        check (attempt_count >= 0)
);

create index idx_edo_import_candidate_header_fingerprint
    on edo_import_candidate using btree (organization_id, header_fingerprint)
    where header_fingerprint is not null;

create index idx_edo_import_candidate_content_fingerprint
    on edo_import_candidate using btree (organization_id, content_fingerprint)
    where content_fingerprint is not null;

create index idx_edo_import_candidate_shared_identity
    on edo_import_candidate using btree (organization_id, shared_document_identity)
    where shared_document_identity is not null;

create unique index ux_edo_import_candidate_imported_purchase
    on edo_import_candidate using btree (imported_purchase_id)
    where imported_purchase_id is not null;

create index idx_edo_import_candidate_job_status_mapping
    on edo_import_candidate using btree (job_id, status, mapping_status);

create index idx_edo_import_candidate_status_attempt
    on edo_import_candidate using btree (status, attempt_count);
