create table edo_import_candidate_line
(
    id                          bigint generated by default as identity not null,
    candidate_id                bigint not null,
    provider_line_number        integer not null,
    catalog_code                character varying(50),
    package_code                character varying(50),
    package_name                character varying(500),
    is_service                  boolean,
    quantity                    numeric(19, 6),
    unit_price                  numeric(24, 8),
    net_amount                  numeric(24, 8),
    vat_rate                    numeric(9, 4),
    vat_amount                  numeric(24, 8),
    total_amount                numeric(24, 8),
    selected_product_id         integer,
    selected_unit_id            smallint,
    selected_vat_rate_id        smallint,
    selected_debit_account_id   integer,
    selected_vat_account_id     integer,
    mapping_status              character varying(30) default 'UNRESOLVED' not null,
    created_date                timestamp without time zone default now() not null,
    updated_date                timestamp without time zone,
    constraint edo_import_candidate_line_pkey primary key (id),
    constraint ux_edo_import_candidate_line_candidate_number
        unique (candidate_id, provider_line_number),
    constraint edo_import_candidate_line_candidate_id_fkey
        foreign key (candidate_id) references edo_import_candidate(id) on delete cascade,
    constraint edo_import_candidate_line_selected_product_id_fkey
        foreign key (selected_product_id) references inv_product(id) on delete set null,
    constraint edo_import_candidate_line_selected_unit_id_fkey
        foreign key (selected_unit_id) references cmn_unit(id) on delete set null,
    constraint edo_import_candidate_line_selected_vat_rate_id_fkey
        foreign key (selected_vat_rate_id) references cmn_vat_rate(id) on delete set null,
    constraint edo_import_candidate_line_selected_debit_account_id_fkey
        foreign key (selected_debit_account_id) references acc_chart_account(id) on delete set null,
    constraint edo_import_candidate_line_selected_vat_account_id_fkey
        foreign key (selected_vat_account_id) references acc_chart_account(id) on delete set null,
    constraint ck_edo_import_candidate_line_number
        check (provider_line_number >= 1),
    constraint ck_edo_import_candidate_line_mapping_status
        check (mapping_status in ('UNRESOLVED', 'PARTIAL', 'RESOLVED'))
);

create index idx_edo_import_candidate_line_mapping_product
    on edo_import_candidate_line using btree (mapping_status, selected_product_id);
