create table edo_import_candidate_marking
(
    id                            bigint generated by default as identity not null,
    candidate_line_id             bigint not null,
    marking_number                character varying(500) not null,
    serial_number                 character varying(250),
    provider_verification_state   character varying(30) default 'UNVERIFIED' not null,
    created_date                  timestamp without time zone default now() not null,
    updated_date                  timestamp without time zone,
    constraint edo_import_candidate_marking_pkey primary key (id),
    constraint ux_edo_import_candidate_marking_line_number
        unique (candidate_line_id, marking_number),
    constraint edo_import_candidate_marking_candidate_line_id_fkey
        foreign key (candidate_line_id) references edo_import_candidate_line(id) on delete cascade,
    constraint ck_edo_import_candidate_marking_verification
        check (provider_verification_state in ('UNVERIFIED', 'VERIFIED', 'MISMATCH'))
);

create index idx_edo_import_candidate_marking_verification
    on edo_import_candidate_marking using btree (provider_verification_state);
