create unique index if not exists ux_inv_product_organization_id_id
    on inv_product (organization_id, id);

create table edo_provider_product_mapping (
    id bigint generated by default as identity primary key,
    organization_id integer not null,
    provider_code character varying(20) not null,
    catalog_code character varying(50) not null,
    package_code character varying(50) not null default '',
    provider_product_name character varying(500) not null,
    provider_product_name_hash character varying(64) not null,
    identity_hash character varying(64) not null,
    is_service boolean not null,
    product_id integer not null,
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    constraint ck_edo_provider_product_mapping_provider
        check (provider_code in ('EDOCS', 'DIDOX')),
    constraint ck_edo_provider_product_mapping_name_hash
        check (provider_product_name_hash ~ '^[0-9a-f]{64}$'),
    constraint ck_edo_provider_product_mapping_identity_hash
        check (identity_hash ~ '^[0-9a-f]{64}$'),
    constraint edo_provider_product_mapping_organization_id_fkey
        foreign key (organization_id) references org_organization(id) on delete restrict,
    constraint edo_provider_product_mapping_product_organization_fkey
        foreign key (organization_id, product_id)
        references inv_product(organization_id, id) on delete restrict
);

create unique index ux_edo_provider_product_mapping_identity
    on edo_provider_product_mapping (organization_id, identity_hash);

create unique index ux_edo_provider_product_mapping_natural_identity
    on edo_provider_product_mapping (
        organization_id,
        provider_code,
        catalog_code,
        package_code,
        provider_product_name_hash,
        is_service);

create index idx_edo_provider_product_mapping_product
    on edo_provider_product_mapping (organization_id, product_id);

comment on table edo_provider_product_mapping is
    'Organization-scoped explicit mapping from an exact EDO provider product identity to a local product.';
