do $$
begin
    if to_regclass('public.edo_import_batch') is not null
       or to_regclass('public.edo_import_batch_document') is not null then
        raise exception 'EDO unified batch schema already exists; refusing partial migration.';
    end if;

    if to_regclass('public.org_organization') is null
       or to_regclass('public.edo_document') is null
       or to_regclass('public.pur_doc') is null
       or to_regclass('public.sale_doc') is null then
        raise exception 'EDO unified batch schema requires organization, EDO, purchase and sale parent tables.';
    end if;
end
$$;

create unique index ux_edo_document_organization_id
    on edo_document (organization_id, id);

create unique index ux_pur_doc_organization_id
    on pur_doc (organization_id, id);

create unique index ux_sale_doc_organization_id
    on sale_doc (organization_id, id);

create table edo_import_batch
(
    id                bigint generated by default as identity not null,
    organization_id   integer not null,
    provider_code     character varying(20) not null,
    plan_hash         character varying(64) not null,
    status            character varying(30) not null,
    idempotency_key   character varying(200),
    created_at        timestamp without time zone default now() not null,
    updated_at        timestamp without time zone,
    completed_at      timestamp without time zone,
    constraint edo_import_batch_pkey primary key (id),
    constraint ux_edo_import_batch_id_organization_provider
        unique (id, organization_id, provider_code),
    constraint edo_import_batch_organization_id_fkey
        foreign key (organization_id) references org_organization(id) on delete restrict,
    constraint ck_edo_import_batch_provider
        check (provider_code = 'EDOCS'),
    constraint ck_edo_import_batch_plan_hash
        check (plan_hash ~ '^[0-9a-f]{64}$'),
    constraint ck_edo_import_batch_status
        check (status in ('PLANNED', 'APPLYING', 'PARTIAL', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

create unique index ux_edo_import_batch_organization_idempotency
    on edo_import_batch (organization_id, idempotency_key)
    where idempotency_key is not null;

create index idx_edo_import_batch_organization_status
    on edo_import_batch (organization_id, status);

create table edo_import_batch_document
(
    id                         bigint generated by default as identity not null,
    batch_id                   bigint not null,
    organization_id            integer not null,
    provider_code              character varying(20) not null,
    provider_document_id       character varying(100) not null,
    edo_document_id            bigint,
    direction                  character varying(10) not null,
    document_type              character varying(50) not null,
    document_number            character varying(100),
    document_date              date,
    status                     character varying(40) not null,
    purchase_document_id       bigint,
    sale_document_id           bigint,
    safe_error_code            character varying(100),
    has_marking                boolean default false not null,
    marking_count              integer default 0 not null,
    marking_verification_state character varying(30),
    marking_source_type        character varying(30),
    sent_override_applied     boolean default false not null,
    created_at                 timestamp without time zone default now() not null,
    updated_at                 timestamp without time zone,
    constraint edo_import_batch_document_pkey primary key (id),
    constraint ux_edo_import_batch_document_organization_batch_provider_document
        unique (organization_id, batch_id, provider_document_id),
    constraint edo_import_batch_document_batch_organization_provider_fkey
        foreign key (batch_id, organization_id, provider_code)
        references edo_import_batch(id, organization_id, provider_code) on delete cascade,
    constraint edo_import_batch_document_organization_id_fkey
        foreign key (organization_id) references org_organization(id) on delete restrict,
    constraint edo_import_batch_document_edo_document_organization_fkey
        foreign key (organization_id, edo_document_id)
        references edo_document(organization_id, id) on delete restrict,
    constraint edo_import_batch_document_purchase_organization_fkey
        foreign key (organization_id, purchase_document_id)
        references pur_doc(organization_id, id) on delete restrict,
    constraint edo_import_batch_document_sale_organization_fkey
        foreign key (organization_id, sale_document_id)
        references sale_doc(organization_id, id) on delete restrict,
    constraint ck_edo_import_batch_document_provider
        check (provider_code = 'EDOCS'),
    constraint ck_edo_import_batch_document_provider_document_id
        check (btrim(provider_document_id) <> ''),
    constraint ck_edo_import_batch_document_direction
        check (direction in ('INBOX', 'OUTBOX')),
    constraint ck_edo_import_batch_document_type
        check (document_type in ('FACTURA', 'WAYBILL_LOCAL')),
    constraint ck_edo_import_batch_document_status
        check (status in ('SIGNED', 'WAITING_FOR_SIGNATURE', 'BLOCKED', 'IMPORTED', 'FAILED', 'ALREADY_IMPORTED', 'NOT_ELIGIBLE')),
    constraint ck_edo_import_batch_document_marking_count
        check (marking_count >= 0),
    constraint ck_edo_import_batch_document_local_link
        check (
            (status in ('IMPORTED', 'ALREADY_IMPORTED') and num_nonnulls(purchase_document_id, sale_document_id) = 1)
            or
            (status not in ('IMPORTED', 'ALREADY_IMPORTED') and num_nonnulls(purchase_document_id, sale_document_id) = 0)
        )
);

create index idx_edo_import_batch_document_organization_status
    on edo_import_batch_document (organization_id, status);
