create table org_organization 
(
    id integer generated by default as identity not null,
    short_name character varying(250) not null,
    full_name character varying(500) not null,
    inn character varying(20) not null,
    phone_number character varying(50),
    region_id integer not null,
    district_id integer,
    address character varying(1000),
    director character varying(250),
    is_parent boolean default false not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    default_language_id smallint,
    tenant_id integer not null references platform_tenant(id),
    setup_status character varying(30) default 'not_started'::character varying not null,
    setup_completed_at timestamp without time zone,
    email character varying(200),
    website character varying(250),
    oked character varying(20),
    constraint org_organization_pkey primary key (id),
    constraint org_organization_default_language_id_fkey foreign key (default_language_id) references cmn_language(id),
    constraint org_organization_district_id_fkey foreign key (district_id) references cmn_district(id),
    constraint org_organization_region_id_fkey foreign key (region_id) references cmn_region(id),
    constraint org_organization_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_org_organization_default_language_id on org_organization using btree (default_language_id);
create index idx_org_organization_district_id on org_organization using btree (district_id);
create index idx_org_organization_full_name on org_organization using btree (full_name);
create index idx_org_organization_inn on org_organization using btree (inn);
create index idx_org_organization_region_id on org_organization using btree (region_id);
create index idx_org_organization_short_name on org_organization using btree (short_name);
create index idx_org_organization_state_id on org_organization using btree (state_id);
create index idx_org_organization_tenant_id on org_organization using btree (tenant_id);
create index idx_org_organization_setup_status on org_organization using btree (setup_status);
