-- Table: public.org_organization

CREATE TABLE public.org_organization (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 14)  NOT NULL,
    short_name character varying(250) NOT NULL,
    full_name character varying(500) NOT NULL,
    inn character varying(20) NOT NULL,
    phone_number character varying(50),
    region_id integer NOT NULL,
    district_id integer,
    address character varying(1000),
    director character varying(250),
    is_parent boolean DEFAULT false NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    default_language_id smallint,
    tenant_id integer,
    setup_status character varying(30) DEFAULT 'not_started'::character varying NOT NULL,
    setup_completed_at timestamp without time zone,
    email character varying(200),
    website character varying(250),
    oked character varying(20),
    CONSTRAINT org_organization_pkey PRIMARY KEY (id),
    CONSTRAINT org_organization_default_language_id_fkey FOREIGN KEY (default_language_id) REFERENCES public.cmn_language(id),
    CONSTRAINT org_organization_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.cmn_district(id),
    CONSTRAINT org_organization_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.cmn_region(id),
    CONSTRAINT org_organization_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id),
    CONSTRAINT org_organization_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.platform_tenant(id)
);

insert into public.org_organization (id, short_name, full_name, inn, phone_number, region_id, district_id, address, director, is_parent, state_id, created_date, default_language_id) values
    ('8', 'baraka_market', 'Baraka market', '1599789', '+998 99 897-06-42', '8', '127', 'Alisher Navoiy 17', 'Hafizov Sardorbek', 'f', '1', '2026-06-12 11:24:38.218896', '1'),
    ('2', 'Najot Ta''lim', 'Najot Ta''lim Xususiy', '310540000', '+998 99 871-23-12', '8', '125', 'Toshkent shahar, Mirzo Ulug''bek tumani, Amir Temur ko''chasi 1-uy test', 'Karimov Jasur test', 't', '1', '2026-06-05 16:49:46.331959', '2');

CREATE INDEX idx_org_organization_default_language_id ON public.org_organization USING btree (default_language_id);

CREATE INDEX idx_org_organization_district_id ON public.org_organization USING btree (district_id);

CREATE INDEX idx_org_organization_full_name ON public.org_organization USING btree (full_name);

CREATE INDEX idx_org_organization_inn ON public.org_organization USING btree (inn);

CREATE INDEX idx_org_organization_region_id ON public.org_organization USING btree (region_id);

CREATE INDEX idx_org_organization_short_name ON public.org_organization USING btree (short_name);

CREATE INDEX idx_org_organization_state_id ON public.org_organization USING btree (state_id);

CREATE INDEX idx_org_organization_tenant_id ON public.org_organization USING btree (tenant_id);

CREATE INDEX idx_org_organization_setup_status ON public.org_organization USING btree (setup_status);
