-- Table: public.org_position

CREATE TABLE public.org_position (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    organization_id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(250) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT org_position_pkey PRIMARY KEY (id),
    CONSTRAINT org_position_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id),
    CONSTRAINT org_position_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

CREATE UNIQUE INDEX idx_org_position_org_code ON public.org_position USING btree (organization_id, code);

CREATE INDEX idx_org_position_organization_id ON public.org_position USING btree (organization_id);

CREATE INDEX idx_org_position_state_id ON public.org_position USING btree (state_id);
