-- Table: public.org_setup_state

CREATE TABLE public.org_setup_state (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    current_step character varying(100) DEFAULT 'organization'::character varying NOT NULL,
    organization_completed boolean DEFAULT false NOT NULL,
    tax_completed boolean DEFAULT false NOT NULL,
    accounting_completed boolean DEFAULT false NOT NULL,
    defaults_completed boolean DEFAULT false NOT NULL,
    users_completed boolean DEFAULT false NOT NULL,
    is_completed boolean DEFAULT false NOT NULL,
    completed_at timestamp without time zone,
    updated_date timestamp without time zone DEFAULT now() NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.org_setup_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_setup_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.org_setup_state_id_seq', 1, false);

ALTER TABLE ONLY public.org_setup_state
    ADD CONSTRAINT org_setup_state_organization_id_key UNIQUE (organization_id);

ALTER TABLE ONLY public.org_setup_state
    ADD CONSTRAINT org_setup_state_pkey PRIMARY KEY (id);

CREATE INDEX idx_org_setup_state_is_completed ON public.org_setup_state USING btree (is_completed);

ALTER TABLE ONLY public.org_setup_state
    ADD CONSTRAINT org_setup_state_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);
