create table org_setup_state 
(
    id integer generated by default as identity not null,
    organization_id integer not null,
    current_step character varying(100) default 'organization'::character varying not null,
    organization_completed boolean default false not null,
    accounting_completed boolean default false not null,
    defaults_completed boolean default false not null,
    users_completed boolean default false not null,
    is_completed boolean default false not null,
    completed_at timestamp without time zone,
    updated_date timestamp without time zone default now() not null,
    created_date timestamp without time zone default now() not null,
    constraint org_setup_state_organization_id_key UNIQUE (organization_id),
    constraint org_setup_state_pkey primary key (id)
);

create index idx_org_setup_state_is_completed on org_setup_state using btree (is_completed);
