-- Table: public.org_tax_settings

CREATE TABLE public.org_tax_settings (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    organization_id integer NOT NULL,
    tax_type_id smallint NOT NULL,
    is_vat_payer boolean DEFAULT false NOT NULL,
    vat_registration_number character varying(100),
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    effective_to date,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_org_tax_settings_dates CHECK (((effective_to IS NULL) OR (effective_to >= effective_from))),
    CONSTRAINT org_tax_settings_pkey PRIMARY KEY (id),
    CONSTRAINT org_tax_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id),
    CONSTRAINT org_tax_settings_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id),
    CONSTRAINT org_tax_settings_tax_type_id_fkey FOREIGN KEY (tax_type_id) REFERENCES public.cmn_tax_type(id)
);

CREATE INDEX idx_org_tax_settings_effective_dates ON public.org_tax_settings USING btree (effective_from, effective_to);

CREATE INDEX idx_org_tax_settings_organization_id ON public.org_tax_settings USING btree (organization_id);

CREATE INDEX idx_org_tax_settings_tax_type_id ON public.org_tax_settings USING btree (tax_type_id);
