-- Table: public.org_tax_settings

CREATE TABLE public.org_tax_settings (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    tax_type_id smallint NOT NULL,
    is_vat_payer boolean DEFAULT false NOT NULL,
    vat_registration_number character varying(100),
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    effective_to date,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_org_tax_settings_dates CHECK (((effective_to IS NULL) OR (effective_to >= effective_from)))
);

ALTER TABLE public.org_tax_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_tax_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.org_tax_settings_id_seq', 1, false);

ALTER TABLE ONLY public.org_tax_settings
    ADD CONSTRAINT org_tax_settings_pkey PRIMARY KEY (id);

CREATE INDEX idx_org_tax_settings_effective_dates ON public.org_tax_settings USING btree (effective_from, effective_to);

CREATE INDEX idx_org_tax_settings_organization_id ON public.org_tax_settings USING btree (organization_id);

CREATE INDEX idx_org_tax_settings_tax_type_id ON public.org_tax_settings USING btree (tax_type_id);

ALTER TABLE ONLY public.org_tax_settings
    ADD CONSTRAINT org_tax_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.org_tax_settings
    ADD CONSTRAINT org_tax_settings_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id);

ALTER TABLE ONLY public.org_tax_settings
    ADD CONSTRAINT org_tax_settings_tax_type_id_fkey FOREIGN KEY (tax_type_id) REFERENCES public.cmn_tax_type(id);
