-- Table: public.org_defaults

CREATE TABLE public.org_defaults (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    branch_id integer,
    warehouse_id integer,
    cash_box_id integer,
    bank_account_id integer,
    receivable_account_id integer,
    payable_account_id integer,
    inventory_account_id integer,
    cash_account_id integer,
    bank_accounting_account_id integer,
    revenue_account_id integer,
    expense_account_id integer,
    cogs_account_id integer,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.org_defaults ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_defaults_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.org_defaults_id_seq', 1, false);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_organization_id_key UNIQUE (organization_id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_pkey PRIMARY KEY (id);

CREATE INDEX idx_org_defaults_bank_account_id ON public.org_defaults USING btree (bank_account_id);

CREATE INDEX idx_org_defaults_branch_id ON public.org_defaults USING btree (branch_id);

CREATE INDEX idx_org_defaults_cash_box_id ON public.org_defaults USING btree (cash_box_id);

CREATE INDEX idx_org_defaults_warehouse_id ON public.org_defaults USING btree (warehouse_id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.org_bank_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_bank_accounting_account_id_fkey FOREIGN KEY (bank_accounting_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.org_branch(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_cash_box_id_fkey FOREIGN KEY (cash_box_id) REFERENCES public.cash_box(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_cogs_account_id_fkey FOREIGN KEY (cogs_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_expense_account_id_fkey FOREIGN KEY (expense_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_inventory_account_id_fkey FOREIGN KEY (inventory_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_payable_account_id_fkey FOREIGN KEY (payable_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_receivable_account_id_fkey FOREIGN KEY (receivable_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_revenue_account_id_fkey FOREIGN KEY (revenue_account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.org_defaults
    ADD CONSTRAINT org_defaults_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouse(id);
