-- Table: public.org_user_invitation

CREATE TABLE public.org_user_invitation (
    id bigint NOT NULL,
    organization_id integer NOT NULL,
    email character varying(200) NOT NULL,
    role_id integer NOT NULL,
    invited_by_user_id integer,
    token_hash character varying(512) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    accepted_at timestamp without time zone,
    accepted_by_user_id integer,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.org_user_invitation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_user_invitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.org_user_invitation_id_seq', 1, false);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_token_hash_key UNIQUE (token_hash);

CREATE INDEX idx_org_user_invitation_email ON public.org_user_invitation USING btree (email);

CREATE INDEX idx_org_user_invitation_organization_id ON public.org_user_invitation USING btree (organization_id);

CREATE INDEX idx_org_user_invitation_role_id ON public.org_user_invitation USING btree (role_id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_accepted_by_user_id_fkey FOREIGN KEY (accepted_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.sys_role(id);

ALTER TABLE ONLY public.org_user_invitation
    ADD CONSTRAINT org_user_invitation_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id);
