-- Table: public.org_claim_request

CREATE TABLE public.org_claim_request (
    id bigint NOT NULL,
    organization_id integer,
    requested_by_user_id integer NOT NULL,
    inn character varying(20) NOT NULL,
    organization_name character varying(500),
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    review_comment character varying(1000),
    reviewed_by_user_id integer,
    reviewed_at timestamp without time zone,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.org_claim_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.org_claim_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.org_claim_request_id_seq', 1, false);

ALTER TABLE ONLY public.org_claim_request
    ADD CONSTRAINT org_claim_request_pkey PRIMARY KEY (id);

CREATE INDEX idx_org_claim_request_inn ON public.org_claim_request USING btree (inn);

CREATE INDEX idx_org_claim_request_organization_id ON public.org_claim_request USING btree (organization_id);

CREATE INDEX idx_org_claim_request_requested_by_user_id ON public.org_claim_request USING btree (requested_by_user_id);

CREATE INDEX idx_org_claim_request_status ON public.org_claim_request USING btree (status);

ALTER TABLE ONLY public.org_claim_request
    ADD CONSTRAINT org_claim_request_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.org_claim_request
    ADD CONSTRAINT org_claim_request_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.org_claim_request
    ADD CONSTRAINT org_claim_request_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.sys_user(id);
