create table if not exists public.org_accounting_policy_version
(
    id integer generated by default as identity not null,
    organization_id integer not null,
    version integer not null,
    effective_from date not null,
    effective_to date,
    inventory_valuation_method character varying(20) not null,
    base_currency_id smallint not null,
    vat_payer boolean not null,
    tax_type_id smallint,
    vat_tax_period character varying(20) not null,
    vat_base_moment character varying(20) not null,
    closed_period_policy character varying(40) not null,
    created_at timestamp without time zone not null,
    created_by_user_id integer not null,
    constraint pk_org_accounting_policy_version primary key (id),
    constraint fk_org_accounting_policy_version_organization
        foreign key (organization_id) references org_organization(id),
    constraint ux_org_accounting_policy_version_org_version
        unique (organization_id, version),
    constraint ck_org_accounting_policy_version_dates
        check ((effective_to is null) or (effective_to >= effective_from))
);

create index if not exists ix_org_accounting_policy_version_effective_dates
    on public.org_accounting_policy_version using btree (effective_from, effective_to);

create index if not exists ix_org_accounting_policy_version_organization_id
    on public.org_accounting_policy_version using btree (organization_id);
