create table acc_chart_account 
(
    id integer generated by default as identity not null,
    parent_id integer,
    code character varying(50),
    name character varying(250) not null,
    is_group boolean default false not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    account_type_id smallint,
    is_quantity boolean default false not null,
    is_currency boolean default false not null,
    number character varying(50) not null,
    organization_id integer not null,
    is_department boolean default false not null,
    is_tax_accounting boolean default false not null,
    is_off_balance boolean default false not null,
    constraint acc_chart_account_pkey primary key (id),
    constraint acc_chart_account_account_type_id_fkey foreign key (account_type_id) references acc_account_type(id),
    constraint acc_chart_account_parent_id_fkey foreign key (parent_id) references acc_chart_account(id) DEFERRABLE INITIALLY DEFERRED,
    constraint acc_chart_account_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint acc_chart_account_organization_id_fkey foreign key (organization_id) references org_organization(id)
);

create index idx_acc_chart_account_account_type_id on acc_chart_account using btree (account_type_id);
create index idx_acc_chart_account_parent_id on acc_chart_account using btree (parent_id);
create index idx_acc_chart_account_state_id on acc_chart_account using btree (state_id);

create unique index ux_acc_chart_account_organization_number
on acc_chart_account (organization_id, number);

create index idx_acc_chart_account_number
on acc_chart_account (number);

