create table acc_chart_account_subkonto 
(
    id integer generated by default as identity not null,
    account_id integer not null,
    subkonto_type_id smallint not null,
    sort_order integer default 0 not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint acc_chart_account_subkonto_pkey primary key (id),
    constraint acc_chart_account_subkonto_account_id_fkey foreign key (account_id) references acc_chart_account(id) on DELETE CASCADE,
    constraint acc_chart_account_subkonto_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint acc_chart_account_subkonto_subkonto_type_id_fkey foreign key (subkonto_type_id) references acc_subkonto_type(id)
);

create index idx_acc_chart_account_subkonto_account_id on acc_chart_account_subkonto using btree (account_id);
create index idx_acc_chart_account_subkonto_type_id on acc_chart_account_subkonto using btree (subkonto_type_id);
