-- Table: public.acc_accounting_policy

CREATE TABLE public.acc_accounting_policy (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 2)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(250) NOT NULL,
    state_id smallint NOT NULL,
    CONSTRAINT acc_accounting_policy_code_key UNIQUE (code),
    CONSTRAINT acc_accounting_policy_pkey PRIMARY KEY (id),
    CONSTRAINT acc_accounting_policy_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.acc_accounting_policy (id, code, name, state_id) values
    ('1', 'STANDARD', 'Стандартная политика РУз', '1');
