-- Table: public.acc_account_resolve_rule

CREATE TABLE public.acc_account_resolve_rule (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 36)  NOT NULL,
    policy_id smallint NOT NULL,
    alias character varying(250) NOT NULL,
    dimension_key character varying(250) NOT NULL,
    dimension_value character varying(250) NOT NULL,
    account_id integer NOT NULL,
    priority integer NOT NULL,
    CONSTRAINT acc_account_resolve_rule_pkey PRIMARY KEY (id),
    CONSTRAINT acc_account_resolve_rule_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.acc_chart_account(id),
    CONSTRAINT acc_account_resolve_rule_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.acc_accounting_policy(id)
);

CREATE SEQUENCE public.acc_account_resolve_rule_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.acc_account_resolve_rule_id_seq OWNED BY public.acc_account_resolve_rule.id;

ALTER TABLE ONLY public.acc_account_resolve_rule ALTER COLUMN id SET DEFAULT nextval('public.acc_account_resolve_rule_id_seq'::regclass);

ALTER TABLE ONLY public.acc_account_resolve_rule
    ADD CONSTRAINT acc_account_resolve_rule_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.acc_account_resolve_rule
    ADD CONSTRAINT acc_account_resolve_rule_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.acc_chart_account(id);

ALTER TABLE ONLY public.acc_account_resolve_rule
    ADD CONSTRAINT acc_account_resolve_rule_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.acc_accounting_policy(id);

-- ===================== Inventory: Товар на складе =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Inventory', '_none', '_default', id, 100 from acc_chart_account where code = '2910';
 
-- ===================== Expense: Расход (услуга) =====================
-- производство → 2010, продажи → 9410, администрирование → 9420, прочее → 9430
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Expense', 'serviceType', 'production', id, 10  from acc_chart_account where code = '2010'
	union all
select 1, 'Expense', 'serviceType', 'sales',       id, 10  from acc_chart_account where code = '9410'
	union all
select 1, 'Expense', 'serviceType', 'admin',       id, 10  from acc_chart_account where code = '9420'
	union all
select 1, 'Expense', 'serviceType', '_default',    id, 100 from acc_chart_account where code = '9430';
 
-- ===================== Supplier / SupplierAdvance =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Supplier',        '_none', '_default', id, 100 from acc_chart_account where code = '6010'
	union all
select 1, 'SupplierAdvance', '_none', '_default', id, 100 from acc_chart_account where code = '4310';
 
-- ===================== Customer / CustomerAdvance =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Customer',        '_none', '_default', id, 100 from acc_chart_account where code = '4010'
	union all
select 1, 'CustomerAdvance', '_none', '_default', id, 100 from acc_chart_account where code = '6310';
 
-- ===================== PaymentAccount: банк/касса =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'PaymentAccount', 'paymentMethod', 'bank',     id, 10  from acc_chart_account where code = '5110'
	union all
select 1, 'PaymentAccount', 'paymentMethod', 'cash',     id, 10  from acc_chart_account where code = '5010'
	union all
select 1, 'PaymentAccount', 'paymentMethod', '_default', id, 100 from acc_chart_account where code = '5110';
 
-- ===================== VAT =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'VATIn',  '_none', '_default', id, 100 from acc_chart_account where code = '4410'
	union all
select 1, 'VATOut', '_none', '_default', id, 100 from acc_chart_account where code = '6410';
 
-- ===================== Revenue =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'SalesRevenue',   '_none', '_default', id, 100 from acc_chart_account where code = '9020'
	union all
select 1, 'ServiceRevenue', '_none', '_default', id, 100 from acc_chart_account where code = '9030';
 
-- ===================== Cost =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'CostOfGoods',   '_none', '_default', id, 100 from acc_chart_account where code = '9120'
	union all
select 1, 'CostOfService', '_none', '_default', id, 100 from acc_chart_account where code = '9130';
 
-- ===================== AssetWriteOff: списание актива =====================
-- счёт приходит явно из кода (2910 или 1010-1090), _default не нужен
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'AssetWriteOff', 'assetType', 'inventory', id, 10 from acc_chart_account where code = '2910';
 
-- ===================== Employee / EmployeeAdvance =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Employee',        '_none', '_default', id, 100 from acc_chart_account where code = '6710'
	union all
select 1, 'EmployeeAdvance', '_none', '_default', id, 100 from acc_chart_account where code = '6970';
 
-- ===================== Founder =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'Founder', '_none', '_default', id, 100 from acc_chart_account where code = '6610';
 
-- ===================== Loan =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'LoanGiven',    '_none', '_default', id, 100 from acc_chart_account where code = '4720'
	union all
select 1, 'LoanReceived', '_none', '_default', id, 100 from acc_chart_account where code = '6810';
 
-- ===================== Налоги =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'TaxVAT',          '_none', '_default', id, 100 from acc_chart_account where code = '6410'
	union all
select 1, 'TaxNDFL',         '_none', '_default', id, 100 from acc_chart_account where code = '6420'
	union all
select 1, 'TaxProfit',       '_none', '_default', id, 100 from acc_chart_account where code = '6430'
	union all
select 1, 'TaxExcise',       '_none', '_default', id, 100 from acc_chart_account where code = '6440'
	union all
select 1, 'TaxProperty',     '_none', '_default', id, 100 from acc_chart_account where code = '6450'
	union all
select 1, 'TaxLand',         '_none', '_default', id, 100 from acc_chart_account where code = '6460'
	union all
select 1, 'TaxOther',        '_none', '_default', id, 100 from acc_chart_account where code = '6490'
	union all
select 1, 'SocialInsurance', '_none', '_default', id, 100 from acc_chart_account where code = '6510'
	union all
select 1, 'PensionFund',     '_none', '_default', id, 100 from acc_chart_account where code = '6530';
 
-- ===================== BankFee =====================
insert into acc_account_resolve_rule (policy_id, alias, dimension_key, dimension_value, account_id, priority)
select 1, 'BankFee', '_none', '_default', id, 100 from acc_chart_account where code = '9430';
