create table acc_posting_batch 
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    document_type_id smallint not null,
    document_id bigint not null,
    status character varying(30) default 'POSTED'::character varying not null,
    posted_by_user_id integer,
    posted_at timestamp without time zone default now() not null,
    reversed_by_user_id integer,
    reversed_at timestamp without time zone,
    comment character varying(1000),
    constraint acc_posting_batch_pkey primary key (id)
);

create index idx_acc_posting_batch_document on acc_posting_batch using btree (document_type_id, document_id);
create unique index ux_acc_posting_batch_document_posted on acc_posting_batch using btree (document_type_id, document_id) WHERE (status = 'POSTED');
create unique index ux_acc_posting_batch_document_reversal on acc_posting_batch using btree (document_type_id, document_id) WHERE (status = 'REVERSAL');
create index idx_acc_posting_batch_organization_id on acc_posting_batch using btree (organization_id);
create index idx_acc_posting_batch_status on acc_posting_batch using btree (status);
