-- Table: public.acc_posting_rule

CREATE TABLE public.acc_posting_rule (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 8)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(250) NOT NULL,
    CONSTRAINT acc_posting_rule_code_key UNIQUE (code),
    CONSTRAINT acc_posting_rule_pkey PRIMARY KEY (id)
);

insert into public.acc_posting_rule (id, code, name) values
    ('1', 'PURCHASE_GOODS', 'Поступление товара'),
    ('2', 'PURCHASE_SERVICE', 'Получение услуги'),
    ('3', 'SALE_GOODS', 'Реализация товара'),
    ('4', 'SALE_SERVICE', 'Оказанная услуга'),
    ('5', 'DEBIT_OPERATION', 'Банковская/кассовая операция — приход'),
    ('6', 'CREDIT_OPERATION', 'Банковская/кассовая операция — расход');

insert into public.acc_posting_rule (id, code, name) values ('7', 'CASH_TRANSFER', 'Kassoviy perevod');
