-- Table: public.acc_accounting_period

CREATE TABLE public.acc_accounting_period (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    organization_id integer NOT NULL,
    year smallint NOT NULL,
    month smallint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_closed boolean DEFAULT false NOT NULL,
    closed_at timestamp without time zone,
    closed_by_user_id integer,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_acc_accounting_period_dates CHECK ((end_date >= start_date)),
    CONSTRAINT ck_acc_accounting_period_month CHECK (((month >= 1) AND (month <= 12))),
    CONSTRAINT acc_accounting_period_pkey PRIMARY KEY (id),
    CONSTRAINT acc_accounting_period_unique_period UNIQUE (organization_id, year, month),
    CONSTRAINT acc_accounting_period_closed_by_user_id_fkey FOREIGN KEY (closed_by_user_id) REFERENCES public.sys_user(id),
    CONSTRAINT acc_accounting_period_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id)
);

CREATE INDEX idx_acc_accounting_period_is_closed ON public.acc_accounting_period USING btree (is_closed);

CREATE INDEX idx_acc_accounting_period_organization_id ON public.acc_accounting_period USING btree (organization_id);
