-- Table: public.acc_posting_batch

CREATE TABLE public.acc_posting_batch (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    organization_id integer NOT NULL,
    document_type_id smallint NOT NULL,
    document_id bigint NOT NULL,
    status character varying(30) DEFAULT 'POSTED'::character varying NOT NULL,
    posted_by_user_id integer,
    posted_at timestamp without time zone DEFAULT now() NOT NULL,
    reversed_by_user_id integer,
    reversed_at timestamp without time zone,
    comment character varying(1000),
    CONSTRAINT acc_posting_batch_pkey PRIMARY KEY (id),
    CONSTRAINT acc_posting_batch_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES public.cmn_document_type(id),
    CONSTRAINT acc_posting_batch_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id),
    CONSTRAINT acc_posting_batch_posted_by_user_id_fkey FOREIGN KEY (posted_by_user_id) REFERENCES public.sys_user(id),
    CONSTRAINT acc_posting_batch_reversed_by_user_id_fkey FOREIGN KEY (reversed_by_user_id) REFERENCES public.sys_user(id)
);

CREATE INDEX idx_acc_posting_batch_document ON public.acc_posting_batch USING btree (document_type_id, document_id);

CREATE UNIQUE INDEX ux_acc_posting_batch_document_posted ON public.acc_posting_batch USING btree (document_type_id, document_id) WHERE (status = 'POSTED');

CREATE UNIQUE INDEX ux_acc_posting_batch_document_reversal ON public.acc_posting_batch USING btree (document_type_id, document_id) WHERE (status = 'REVERSAL');

CREATE INDEX idx_acc_posting_batch_organization_id ON public.acc_posting_batch USING btree (organization_id);

CREATE INDEX idx_acc_posting_batch_status ON public.acc_posting_batch USING btree (status);
