-- Table: public.acc_posting_batch

CREATE TABLE public.acc_posting_batch (
    id bigint NOT NULL,
    organization_id integer NOT NULL,
    document_type_id smallint NOT NULL,
    document_id bigint NOT NULL,
    status character varying(30) DEFAULT 'posted'::character varying NOT NULL,
    posted_by_user_id integer,
    posted_at timestamp without time zone DEFAULT now() NOT NULL,
    reversed_by_user_id integer,
    reversed_at timestamp without time zone,
    comment character varying(1000)
);

ALTER TABLE public.acc_posting_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acc_posting_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.acc_posting_batch_id_seq', 1, false);

ALTER TABLE ONLY public.acc_posting_batch
    ADD CONSTRAINT acc_posting_batch_pkey PRIMARY KEY (id);

CREATE INDEX idx_acc_posting_batch_document ON public.acc_posting_batch USING btree (document_type_id, document_id);

CREATE INDEX idx_acc_posting_batch_organization_id ON public.acc_posting_batch USING btree (organization_id);

CREATE INDEX idx_acc_posting_batch_status ON public.acc_posting_batch USING btree (status);

ALTER TABLE ONLY public.acc_posting_batch
    ADD CONSTRAINT acc_posting_batch_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES public.cmn_document_type(id);

ALTER TABLE ONLY public.acc_posting_batch
    ADD CONSTRAINT acc_posting_batch_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.acc_posting_batch
    ADD CONSTRAINT acc_posting_batch_posted_by_user_id_fkey FOREIGN KEY (posted_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.acc_posting_batch
    ADD CONSTRAINT acc_posting_batch_reversed_by_user_id_fkey FOREIGN KEY (reversed_by_user_id) REFERENCES public.sys_user(id);
