-- Table: public.platform_tenant

CREATE TABLE public.platform_tenant (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    name character varying(250) NOT NULL,
    slug character varying(150) NOT NULL,
    owner_user_id integer,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    updated_date timestamp without time zone,
    CONSTRAINT platform_tenant_pkey PRIMARY KEY (id),
    CONSTRAINT platform_tenant_slug_key UNIQUE (slug),
    CONSTRAINT platform_tenant_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.sys_user(id),
    CONSTRAINT platform_tenant_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

CREATE INDEX idx_platform_tenant_owner_user_id ON public.platform_tenant USING btree (owner_user_id);

CREATE INDEX idx_platform_tenant_state_id ON public.platform_tenant USING btree (state_id);
