-- Table: public.platform_tenant

CREATE TABLE public.platform_tenant (
    id integer NOT NULL,
    name character varying(250) NOT NULL,
    slug character varying(150) NOT NULL,
    owner_user_id integer,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    updated_date timestamp without time zone
);

ALTER TABLE public.platform_tenant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_tenant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.platform_tenant_id_seq', 1, false);

ALTER TABLE ONLY public.platform_tenant
    ADD CONSTRAINT platform_tenant_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.platform_tenant
    ADD CONSTRAINT platform_tenant_slug_key UNIQUE (slug);

CREATE INDEX idx_platform_tenant_owner_user_id ON public.platform_tenant USING btree (owner_user_id);

CREATE INDEX idx_platform_tenant_state_id ON public.platform_tenant USING btree (state_id);

ALTER TABLE ONLY public.platform_tenant
    ADD CONSTRAINT platform_tenant_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.platform_tenant
    ADD CONSTRAINT platform_tenant_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id);
