create table sys_module_sub_group
(
    id integer generated by default as identity not null,
    code character varying(100) not null,
    short_name character varying(250) not null,
    full_name character varying(300) not null,
    created_date timestamp without time zone default now() not null,
    constraint sys_module_sub_group_pkey primary key (id)
);
create unique index sys_module_sub_group_unique_index_code on sys_module_sub_group using btree (code);
