create table sys_module
(
    id integer generated by default as identity not null,
    code character varying(100) not null,
    short_name character varying(250) not null,
    full_name character varying(300) not null,
    sub_group_id integer not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    parent_id integer,
    route character varying(250),
    icon character varying(100),
    sort_order integer default 0 not null,
    is_visible boolean default true not null,
    constraint sys_module_pkey primary key (id),
    constraint sys_module_state_id_fkey foreign key (state_id) references cmn_state (id),
    constraint sys_module_sub_group_id_fkey foreign key (sub_group_id) references sys_module_sub_group (id),
    constraint sys_module_parent_id_fkey foreign key (parent_id) references sys_module (id) DEFERRABLE INITIALLY DEFERRED
);

create unique index sys_module_unique_index_code on sys_module using btree (code);
create index sys_module_unique_index_sub_group_id on sys_module using btree (sub_group_id);
create index idx_sys_module_parent_id on sys_module using btree (parent_id);
create index idx_sys_module_sort_order on sys_module using btree (sort_order);
create index idx_sys_module_is_visible on sys_module using btree (is_visible);
