create table sys_role 
(
    id                      integer generated by default as identity not null,
    short_name              character varying(100) not null,
    full_name               character varying(255) not null,
    state_id                smallint not null,
    created_date            timestamp without time zone default now() not null,
    organization_id         integer,
    has_global_access       boolean default false not null,
    code                    character varying(100),
    description             character varying(500),
    is_system               boolean default false not null,
    is_owner_role           boolean default false not null,
    sort_order              integer default 0 not null,

    constraint sys_role_pkey primary key (id),
    constraint sys_role_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint sys_role_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_sys_role_organization_id 
    on sys_role using btree (organization_id);

create index idx_sys_role_code 
    on sys_role using btree (code);

create index idx_sys_role_is_system 
    on sys_role using btree (is_system);

create index idx_sys_role_sort_order 
    on sys_role using btree (sort_order);

create unique index uidx_sys_role_org_code 
    on sys_role using btree (organization_id, code) WHERE (code IS not null);
