-- Table: public.sys_refresh_token

CREATE TABLE public.sys_refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(512) NOT NULL,
    jwt_id character varying(128),
    device_name character varying(250),
    ip_address character varying(64),
    user_agent character varying(500),
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    replaced_by_token_hash character varying(512),
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT sys_refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT sys_refresh_token_token_hash_key UNIQUE (token_hash),
    CONSTRAINT sys_refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id)
);

CREATE INDEX idx_sys_refresh_token_expires_at ON public.sys_refresh_token USING btree (expires_at);

CREATE INDEX idx_sys_refresh_token_revoked_at ON public.sys_refresh_token USING btree (revoked_at);

CREATE INDEX idx_sys_refresh_token_user_id ON public.sys_refresh_token USING btree (user_id);
