-- Table: public.sys_email_verification_token

CREATE TABLE public.sys_email_verification_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(512) NOT NULL,
    email character varying(200) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified_at timestamp without time zone,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT sys_email_verification_token_pkey PRIMARY KEY (id),
    CONSTRAINT sys_email_verification_token_token_hash_key UNIQUE (token_hash),
    CONSTRAINT sys_email_verification_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id)
);

CREATE INDEX idx_sys_email_verification_token_email ON public.sys_email_verification_token USING btree (email);

CREATE INDEX idx_sys_email_verification_token_user_id ON public.sys_email_verification_token USING btree (user_id);
