-- Table: public.sys_email_verification_token

CREATE TABLE public.sys_email_verification_token (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(512) NOT NULL,
    email character varying(200) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    verified_at timestamp without time zone,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.sys_email_verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_email_verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.sys_email_verification_token_id_seq', 1, false);

ALTER TABLE ONLY public.sys_email_verification_token
    ADD CONSTRAINT sys_email_verification_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sys_email_verification_token
    ADD CONSTRAINT sys_email_verification_token_token_hash_key UNIQUE (token_hash);

CREATE INDEX idx_sys_email_verification_token_email ON public.sys_email_verification_token USING btree (email);

CREATE INDEX idx_sys_email_verification_token_user_id ON public.sys_email_verification_token USING btree (user_id);

ALTER TABLE ONLY public.sys_email_verification_token
    ADD CONSTRAINT sys_email_verification_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);
