create table sys_password_reset_token 
(
    id bigint generated by default as identity not null,
    user_id integer not null,
    token_hash character varying(512) not null,
    expires_at timestamp without time zone not null,
    used_at timestamp without time zone,
    created_date timestamp without time zone default now() not null,
    constraint sys_password_reset_token_pkey primary key (id),
    constraint sys_password_reset_token_token_hash_key UNIQUE (token_hash)
);

create index idx_sys_password_reset_token_expires_at on sys_password_reset_token using btree (expires_at);
create index idx_sys_password_reset_token_user_id on sys_password_reset_token using btree (user_id);

