create table inv_reg_balance
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    document_type_id smallint not null,
    document_id bigint not null,
    warehouse_id integer not null,
    product_id integer not null,
    operation_type_id smallint not null,
    quantity numeric(18,3) not null,
    amount numeric(18,2) not null,
    doc_date timestamp without time zone not null,
    created_date timestamp without time zone default now() not null,
    posting_batch_id bigint,
    source_line_id bigint,
    reversal_entry_id bigint,
    product_table_id integer,
    constraint inv_reg_balance_pkey primary key (id),
    constraint inv_reg_balance_document_type_id_fkey foreign key (document_type_id) references cmn_document_type(id),
    constraint inv_reg_balance_operation_type_id_fkey foreign key (operation_type_id) references cmn_operation_type(id),
    constraint inv_reg_balance_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint inv_reg_balance_product_id_fkey foreign key (product_id) references inv_product(id),
    constraint inv_reg_balance_product_table_id_fkey foreign key (product_table_id) references inv_product_table(id),
    constraint inv_reg_balance_warehouse_id_fkey foreign key (warehouse_id) references inv_warehouse(id)
);

create index idx_inv_reg_balance_doc_date on inv_reg_balance using btree (doc_date);
create index idx_inv_reg_balance_document on inv_reg_balance using btree (document_type_id, document_id);
create unique index idx_inv_reg_balance_document_product_id on inv_reg_balance using btree (document_type_id, document_id, product_id, product_table_id);
create index idx_inv_reg_balance_organization_id on inv_reg_balance using btree (organization_id);
create index idx_inv_reg_balance_posting_batch_id on inv_reg_balance using btree (posting_batch_id);
create index idx_inv_reg_balance_product_id on inv_reg_balance using btree (product_id);
create index idx_inv_reg_balance_product_table_id on inv_reg_balance using btree (product_table_id);
create index idx_inv_reg_balance_reversal_entry_id on inv_reg_balance using btree (reversal_entry_id);
create index idx_inv_reg_balance_warehouse_id on inv_reg_balance using btree (warehouse_id);
