using Npgsql;

namespace IntegrationTests;

public sealed class PurchaseDocNumberTriggerPostgresTests
{
    private const string TestConnectionEnvironmentVariable = "ACCOUNTING_TEST_POSTGRES_CONNECTION";

    [Fact]
    public async Task PostgreSql_trigger_preserves_explicit_historical_number_and_generates_legacy_fallback()
    {
        var connectionString = Environment.GetEnvironmentVariable(TestConnectionEnvironmentVariable);
        if (string.IsNullOrWhiteSpace(connectionString))
            return;

        var migration = await File.ReadAllTextAsync(FindMigrationPath());
        Assert.Contains("if new.doc_number is not null and btrim(new.doc_number) <> '' then", migration,
            StringComparison.OrdinalIgnoreCase);
        Assert.Contains("where doc_number ~ '^[0-9]+$'", migration, StringComparison.Ordinal);

        var schemaName = "pur_doc_trigger_test_" + Guid.NewGuid().ToString("N");
        var qualifiedSchema = $"\"{schemaName}\"";
        var functionSql = migration.Replace(
            "set_pur_doc_number()",
            $"{qualifiedSchema}.set_pur_doc_number()",
            StringComparison.OrdinalIgnoreCase);

        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        await ExecuteAsync(connection, transaction, $"create schema {qualifiedSchema};");
        await ExecuteAsync(connection, transaction, $"set local search_path to {qualifiedSchema};");
        await ExecuteAsync(connection, transaction, """
            create table pur_doc
            (
                id bigint generated by default as identity primary key,
                doc_number varchar(100)
            );
            """);
        await ExecuteAsync(connection, transaction, functionSql);
        await ExecuteAsync(connection, transaction, $"""
            create trigger set_pur_doc_number_before_insert
            before insert on pur_doc
            for each row execute function {qualifiedSchema}.set_pur_doc_number();
            """);

        var explicitNumber = await ExecuteScalarAsync(
            connection, transaction,
            "insert into pur_doc (doc_number) values ('H-2026-1') returning doc_number;");
        var generatedNumber = await ExecuteScalarAsync(
            connection, transaction,
            "insert into pur_doc (doc_number) values ('   ') returning doc_number;");

        Assert.Equal("H-2026-1", explicitNumber);
        Assert.Equal("100000001", generatedNumber);
        await transaction.RollbackAsync();
    }

    private static async Task ExecuteAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection, transaction);
        await command.ExecuteNonQueryAsync();
    }

    private static async Task<string?> ExecuteScalarAsync(
        NpgsqlConnection connection,
        NpgsqlTransaction transaction,
        string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection, transaction);
        return (string?)await command.ExecuteScalarAsync();
    }

    private static string FindMigrationPath()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            var candidate = Path.Combine(
                directory.FullName,
                "src",
                "Infrastructure",
                "Persistence",
                "Scripts",
                "07_pur",
                "0705_preserve_explicit_pur_doc_number.sql");
            if (File.Exists(candidate))
                return candidate;
        }

        throw new FileNotFoundException("Purchase document number trigger migration was not found.");
    }
}
