-- Table: public.inv_product_group

CREATE TABLE public.inv_product_group (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 15)  NOT NULL,
    organization_id integer NOT NULL,
    name character varying(250) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    code character varying(100),
    parent_id integer,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT inv_product_group_pkey PRIMARY KEY (id),
    CONSTRAINT inv_product_group_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id),
    CONSTRAINT inv_product_group_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id),
    CONSTRAINT inv_product_group_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.inv_product_group(id)
);

insert into public.inv_product_group (id, organization_id, name, state_id, created_date) values
    ('13', '8', 'Muzlatgichlar', '1', '2026-06-27 15:18:21.48753'),
    ('14', '8', 'Komunnal xizmatlar', '1', '2026-06-27 15:21:30.13086');

CREATE INDEX idx_inv_product_group_organization_id ON public.inv_product_group USING btree (organization_id);

CREATE INDEX idx_inv_product_group_state_id ON public.inv_product_group USING btree (state_id);

CREATE INDEX idx_inv_product_group_code ON public.inv_product_group USING btree (code);

CREATE INDEX idx_inv_product_group_parent_id ON public.inv_product_group USING btree (parent_id);

CREATE INDEX idx_inv_product_group_sort_order ON public.inv_product_group USING btree (sort_order);

CREATE UNIQUE INDEX uidx_inv_product_group_org_code ON public.inv_product_group USING btree (organization_id, code) WHERE (code IS NOT NULL);
