create table inv_product_table 
(
    id integer generated by default as identity not null,
    product_id integer not null,
    organization_id integer not null,
    current_warehouse_id integer,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    serial_number character varying(250),
    marking_number character varying(250),
    status_id smallint default 1 not null,
    constraint inv_product_table_pkey primary key (id),
    constraint inv_product_table_current_warehouse_id_fkey foreign key (current_warehouse_id) references inv_warehouse(id),
    constraint inv_product_table_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint inv_product_table_product_id_fkey foreign key (product_id) references inv_product(id),
    constraint inv_product_table_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint inv_product_table_status_id_fkey foreign key (status_id) references cmn_product_table_status(id)
);

create index ix_inv_product_table_status_id on inv_product_table using btree (status_id);
create index idx_inv_product_table_current_warehouse_id on inv_product_table using btree (current_warehouse_id);
create index idx_inv_product_table_org_warehouse_status on inv_product_table using btree (organization_id, current_warehouse_id, status_id);
create index idx_inv_product_table_org_warehouse_status_product on inv_product_table using btree (organization_id, current_warehouse_id, status_id, product_id);
create unique index ux_inv_product_table_org_marking on inv_product_table using btree (organization_id, marking_number) WHERE (marking_number IS not null);
create unique index ux_inv_product_table_org_serial on inv_product_table using btree (organization_id, serial_number) WHERE (serial_number IS not null);

insert into inv_product_table (id, product_id, organization_id, state_id, created_date, serial_number, marking_number, status_id) values
    ('455', '23', '8', '1', '2026-06-27 18:07:17.497344', null, '0104780074206893217UkCJ6Gu*gG_j.wf6WnX91XUWh92JkB/xWNpbjVhcmtkWVdsT3lhVTVhYjdUQm8yQgOW3lE=', '1'),
    ('456', '23', '8', '1', '2026-06-27 18:07:17.497737', null, '010478007420371721NZVF0x+-fnd<lcpI11Wc91UZF092SDB2UZccAGRfCmSPNYJYumzGxmcnTaumTSS1HOIBuOE=', '1'),
    ('457', '23', '8', '1', '2026-06-27 18:07:17.497799', null, '0104780074203717210t*wRjFf>m9eK-''dqeRV91UZF092b0xBdzcw+3GSPfZP95mjWrYDKhom4PWWecsUayvv2sQ=', '1'),
    ('458', '23', '8', '1', '2026-06-27 18:07:17.497799', null, '010478010915122821)nUfDN1p=8G.G2nk8_sJ91UZF092d3lJcOvPHgtC3DxncIcpDZVxRY9BDkfyC1+gYcgxFyQ=', '1'),
    ('459', '23', '8', '1', '2026-06-29 14:59:14.793003', null, 'qwdqdqwdqwdqwdqdqd', '1'),
    ('460', '23', '8', '1', '2026-06-29 14:59:14.793431', null, 'qdqdqdqdqdqdqdqdqdq2855', '1'),
    ('461', '23', '8', '1', '2026-06-29 14:59:14.793497', null, 'qdqdqdqdqdq98d4q8d789qwd7q', '1'),
    ('463', '24', '8', '1', '2026-06-29 15:01:54.008417', null, 'aohjfoiwhio', '1'),
    ('462', '24', '8', '1', '2026-06-29 15:01:54.008414', null, 'fwliejfoiwjfopwjp''ef856', '2');
