create table inv_product_table 
(
    id integer generated by default as identity not null,
    product_id integer not null,
    created_date timestamp without time zone default now() not null,
    serial_number character varying(250),
    marking_number character varying(250),
    constraint inv_product_table_pkey primary key (id),
    constraint inv_product_table_product_id_fkey foreign key (product_id) references inv_product(id)
);

insert into inv_product_table (id, product_id, created_date, serial_number, marking_number) values
    ('455', '23', '2026-06-27 18:07:17.497344', null, '0104780074206893217UkCJ6Gu*gG_j.wf6WnX91XUWh92JkB/xWNpbjVhcmtkWVdsT3lhVTVhYjdUQm8yQgOW3lE='),
    ('456', '23', '2026-06-27 18:07:17.497737', null, '010478007420371721NZVF0x+-fnd<lcpI11Wc91UZF092SDB2UZccAGRfCmSPNYJYumzGxmcnTaumTSS1HOIBuOE='),
    ('457', '23', '2026-06-27 18:07:17.497799', null, '0104780074203717210t*wRjFf>m9eK-''dqeRV91UZF092b0xBdzcw+3GSPfZP95mjWrYDKhom4PWWecsUayvv2sQ='),
    ('458', '23', '2026-06-27 18:07:17.497799', null, '010478010915122821)nUfDN1p=8G.G2nk8_sJ91UZF092d3lJcOvPHgtC3DxncIcpDZVxRY9BDkfyC1+gYcgxFyQ='),
    ('459', '23', '2026-06-29 14:59:14.793003', null, 'qwdqdqwdqwdqwdqdqd'),
    ('460', '23', '2026-06-29 14:59:14.793431', null, 'qdqdqdqdqdqdqdqdqdq2855'),
    ('461', '23', '2026-06-29 14:59:14.793497', null, 'qdqdqdqdqdq98d4q8d789qwd7q'),
    ('463', '24', '2026-06-29 15:01:54.008417', null, 'aohjfoiwhio'),
    ('462', '24', '2026-06-29 15:01:54.008414', null, 'fwliejfoiwjfopwjp''ef856');
