create table inv_inventory_count_line
(
    id bigint generated by default as identity primary key,
    owner_id bigint not null references inv_inventory_count_doc(id) on delete cascade,
    product_id integer not null references inv_product(id),
    unit_id smallint not null references cmn_unit(id),
    counted_quantity numeric(24,8) not null,
    default_cost_price numeric(24,8) not null,
    comment varchar(1000)
);

create index ix_inv_inventory_count_line_owner_id on inv_inventory_count_line (owner_id);
create index idx_inv_inventory_count_line_product_id on inv_inventory_count_line (product_id);
create index idx_inv_inventory_count_line_unit_id on inv_inventory_count_line (unit_id);
create unique index ux_inv_inventory_count_line_owner_product_unit on inv_inventory_count_line (owner_id, product_id, unit_id);
