create table inv_product_didox_profile
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    product_id integer not null,
    default_origin_code smallint not null,
    effective_from date not null,
    effective_to date,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint ck_inv_product_didox_profile_dates check ((effective_to is null) or (effective_to >= effective_from)),
    constraint inv_product_didox_profile_pkey primary key (id),
    constraint inv_product_didox_profile_default_origin_code_fkey foreign key (default_origin_code) references cmn_didox_origin(code),
    constraint inv_product_didox_profile_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint inv_product_didox_profile_product_id_fkey foreign key (product_id) references inv_product(id),
    constraint inv_product_didox_profile_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_inv_product_didox_profile_effective_dates on inv_product_didox_profile using btree (effective_from, effective_to);
create index idx_inv_product_didox_profile_organization_id on inv_product_didox_profile using btree (organization_id);
create index idx_inv_product_didox_profile_product_id on inv_product_didox_profile using btree (product_id);
create index idx_inv_product_didox_profile_state_id on inv_product_didox_profile using btree (state_id);
create unique index ux_inv_product_didox_profile_product_effective_from on inv_product_didox_profile using btree (product_id, effective_from);
