create table inv_product_table_didox_origin
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    product_table_id integer not null,
    origin_code smallint not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint inv_product_table_didox_origin_pkey primary key (id),
    constraint inv_product_table_didox_origin_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint inv_product_table_didox_origin_origin_code_fkey foreign key (origin_code) references cmn_didox_origin(code),
    constraint inv_product_table_didox_origin_product_table_id_fkey foreign key (product_table_id) references inv_product_table(id),
    constraint inv_product_table_didox_origin_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_inv_product_table_didox_origin_organization_id on inv_product_table_didox_origin using btree (organization_id);
create index idx_inv_product_table_didox_origin_origin_code on inv_product_table_didox_origin using btree (origin_code);
create index idx_inv_product_table_didox_origin_state_id on inv_product_table_didox_origin using btree (state_id);
create unique index ux_inv_product_table_didox_origin_product_table on inv_product_table_didox_origin using btree (product_table_id);
