namespace Application.Features.RegulatedObligationSettings;

public sealed class RegulatedObligationSettingCreateDtoValidator
    : RegulatedObligationSettingBaseDtoValidator<RegulatedObligationSettingCreateDto>;
