namespace Application.Features.RegulatedObligationSettings;

public sealed class RegulatedObligationSettingUpdateDtoValidator
    : RegulatedObligationSettingBaseDtoValidator<RegulatedObligationSettingUpdateDto>;
