create table pay_employee
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    employee_number varchar(50) not null,
    pinfl varchar(14),
    tin varchar(20),
    first_name varchar(150) not null,
    last_name varchar(150) not null,
    middle_name varchar(150),
    birth_date date,
    phone_number varchar(50),
    email varchar(200),
    bank_account_number varchar(100),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    created_by_user_id integer references sys_user(id),
    updated_by_user_id integer references sys_user(id),
    constraint pay_employee_pkey primary key (id),
    constraint ck_pay_employee_pinfl check (pinfl is null or length(pinfl) = 14),
    constraint ux_pay_employee_org_number unique (organization_id, employee_number)
);

create index idx_pay_employee_organization_id on pay_employee (organization_id);
create index idx_pay_employee_state_id on pay_employee (state_id);
create index idx_pay_employee_name on pay_employee (last_name, first_name);
create unique index ux_pay_employee_org_pinfl
    on pay_employee (organization_id, pinfl)
    where pinfl is not null;
