create table pay_employment
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    employee_id bigint not null references pay_employee(id),
    department_id integer references org_department(id),
    position_id integer references org_position(id),
    employment_type varchar(30) not null default 'PRIMARY',
    start_date date not null,
    end_date date,
    monthly_salary numeric(18,2) not null,
    employment_rate numeric(5,4) not null default 1,
    weekly_hours numeric(6,2) not null default 40,
    currency_id smallint not null references cmn_currency(id),
    expense_account_id integer references acc_chart_account(id),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    constraint pay_employment_pkey primary key (id),
    constraint ck_pay_employment_type
        check (employment_type in ('PRIMARY', 'PART_TIME', 'CONTRACT')),
    constraint ck_pay_employment_dates
        check (end_date is null or end_date >= start_date),
    constraint ck_pay_employment_salary check (monthly_salary >= 0),
    constraint ck_pay_employment_rate check (employment_rate > 0 and employment_rate <= 2),
    constraint ck_pay_employment_weekly_hours check (weekly_hours > 0 and weekly_hours <= 168),
    constraint ux_pay_employment_employee_start unique (employee_id, start_date)
);

create index idx_pay_employment_organization_id on pay_employment (organization_id);
create index idx_pay_employment_employee_id on pay_employment (employee_id);
create index idx_pay_employment_department_id on pay_employment (department_id);
create index idx_pay_employment_position_id on pay_employment (position_id);
create index idx_pay_employment_dates on pay_employment (start_date, end_date);
create index idx_pay_employment_state_id on pay_employment (state_id);
