create table pay_component
(
    id integer generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    code varchar(50) not null,
    name varchar(250) not null,
    component_type varchar(30) not null,
    calculation_method varchar(30) not null,
    default_amount numeric(18,2),
    default_rate numeric(9,4),
    is_mandatory boolean not null default false,
    expense_account_id integer references acc_chart_account(id),
    liability_account_id integer references acc_chart_account(id),
    effective_from date not null,
    effective_to date,
    sort_order integer not null default 1,
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    constraint pay_component_pkey primary key (id),
    constraint ck_pay_component_type
        check (component_type in ('EARNING', 'DEDUCTION', 'EMPLOYER_TAX')),
    constraint ck_pay_component_method
        check (calculation_method in ('SALARY_PRORATED', 'FIXED', 'PERCENT_OF_GROSS', 'PER_HOUR')),
    constraint ck_pay_component_default_amount
        check (default_amount is null or default_amount >= 0),
    constraint ck_pay_component_default_rate
        check (default_rate is null or default_rate >= 0),
    constraint ck_pay_component_dates
        check (effective_to is null or effective_to >= effective_from),
    constraint ck_pay_component_sort_order check (sort_order > 0),
    constraint ux_pay_component_org_code_from unique (organization_id, code, effective_from)
);

create index idx_pay_component_organization_id on pay_component (organization_id);
create index idx_pay_component_type on pay_component (component_type);
create index idx_pay_component_effective_dates on pay_component (effective_from, effective_to);
create index idx_pay_component_state_id on pay_component (state_id);
