create table pay_employee_component
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    employee_id bigint not null references pay_employee(id),
    component_id integer not null references pay_component(id),
    amount numeric(18,2),
    rate numeric(9,4),
    effective_from date not null,
    effective_to date,
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    constraint pay_employee_component_pkey primary key (id),
    constraint ck_pay_employee_component_amount check (amount is null or amount >= 0),
    constraint ck_pay_employee_component_rate check (rate is null or rate >= 0),
    constraint ck_pay_employee_component_dates
        check (effective_to is null or effective_to >= effective_from),
    constraint ux_pay_employee_component_period
        unique (employee_id, component_id, effective_from)
);

create index idx_pay_employee_component_organization_id on pay_employee_component (organization_id);
create index idx_pay_employee_component_employee_id on pay_employee_component (employee_id);
create index idx_pay_employee_component_component_id on pay_employee_component (component_id);
create index idx_pay_employee_component_effective_dates on pay_employee_component (effective_from, effective_to);
