create table pay_period
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    period_year smallint not null,
    period_month smallint not null,
    start_date date not null,
    end_date date not null,
    norm_work_days numeric(6,2) not null,
    norm_work_hours numeric(8,2) not null,
    status varchar(20) not null default 'OPEN',
    created_date timestamp without time zone not null default now(),
    closed_date timestamp without time zone,
    closed_by_user_id integer references sys_user(id),
    constraint pay_period_pkey primary key (id),
    constraint ck_pay_period_year check (period_year between 2000 and 2200),
    constraint ck_pay_period_month check (period_month between 1 and 12),
    constraint ck_pay_period_dates check (end_date >= start_date),
    constraint ck_pay_period_norm_days check (norm_work_days > 0),
    constraint ck_pay_period_norm_hours check (norm_work_hours > 0),
    constraint ck_pay_period_status check (status in ('OPEN', 'CLOSED')),
    constraint ux_pay_period_org_year_month unique (organization_id, period_year, period_month)
);

create index idx_pay_period_organization_id on pay_period (organization_id);
create index idx_pay_period_dates on pay_period (start_date, end_date);
create index idx_pay_period_status on pay_period (status);
