create table pay_timesheet
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    period_id bigint not null references pay_period(id),
    doc_number varchar(100) not null,
    doc_date timestamp without time zone not null,
    status_id smallint not null references cmn_document_status(id),
    note varchar(1000),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    created_by_user_id integer references sys_user(id),
    updated_date timestamp without time zone,
    updated_by_user_id integer references sys_user(id),
    posted_at timestamp without time zone,
    posted_by_user_id integer references sys_user(id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer references sys_user(id),
    constraint pay_timesheet_pkey primary key (id),
    constraint ux_pay_timesheet_org_doc_number unique (organization_id, doc_number)
);

create index idx_pay_timesheet_organization_id on pay_timesheet (organization_id);
create index idx_pay_timesheet_period_id on pay_timesheet (period_id);
create index idx_pay_timesheet_status_id on pay_timesheet (status_id);
create index idx_pay_timesheet_state_id on pay_timesheet (state_id);
create unique index ux_pay_timesheet_active_period
    on pay_timesheet (organization_id, period_id)
    where status_id <> 3 and state_id = 1;
