create table pay_timesheet_line
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    timesheet_id bigint not null references pay_timesheet(id) on delete cascade,
    employee_id bigint not null references pay_employee(id),
    worked_days numeric(6,2) not null default 0,
    worked_hours numeric(8,2) not null default 0,
    leave_days numeric(6,2) not null default 0,
    sick_days numeric(6,2) not null default 0,
    absent_days numeric(6,2) not null default 0,
    overtime_hours numeric(8,2) not null default 0,
    note varchar(500),
    constraint pay_timesheet_line_pkey primary key (id),
    constraint ck_pay_timesheet_line_values check (
        worked_days >= 0 and worked_hours >= 0 and leave_days >= 0
        and sick_days >= 0 and absent_days >= 0 and overtime_hours >= 0
    ),
    constraint ux_pay_timesheet_line_employee unique (timesheet_id, employee_id)
);

create index idx_pay_timesheet_line_organization_id on pay_timesheet_line (organization_id);
create index idx_pay_timesheet_line_timesheet_id on pay_timesheet_line (timesheet_id);
create index idx_pay_timesheet_line_employee_id on pay_timesheet_line (employee_id);
