create table pay_payroll_doc
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    period_id bigint not null references pay_period(id),
    doc_number varchar(100) not null,
    doc_date timestamp without time zone not null,
    document_kind varchar(20) not null default 'REGULAR',
    correction_of_doc_id bigint references pay_payroll_doc(id),
    currency_id smallint not null references cmn_currency(id),
    status_id smallint not null references cmn_document_status(id),
    gross_amount numeric(18,2) not null default 0,
    deduction_amount numeric(18,2) not null default 0,
    employer_tax_amount numeric(18,2) not null default 0,
    advance_amount numeric(18,2) not null default 0,
    net_amount numeric(18,2) not null default 0,
    payable_amount numeric(18,2) not null default 0,
    note varchar(1000),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    created_by_user_id integer references sys_user(id),
    updated_date timestamp without time zone,
    updated_by_user_id integer references sys_user(id),
    posted_at timestamp without time zone,
    posted_by_user_id integer references sys_user(id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer references sys_user(id),
    constraint pay_payroll_doc_pkey primary key (id),
    constraint ck_pay_payroll_doc_kind
        check (document_kind in ('REGULAR', 'CORRECTION')),
    constraint ck_pay_payroll_doc_correction check (
        (document_kind = 'REGULAR' and correction_of_doc_id is null)
        or (document_kind = 'CORRECTION' and correction_of_doc_id is not null)
    ),
    constraint ux_pay_payroll_doc_org_doc_number unique (organization_id, doc_number)
);

create index idx_pay_payroll_doc_organization_id on pay_payroll_doc (organization_id);
create index idx_pay_payroll_doc_period_id on pay_payroll_doc (period_id);
create index idx_pay_payroll_doc_status_id on pay_payroll_doc (status_id);
create index idx_pay_payroll_doc_correction_of on pay_payroll_doc (correction_of_doc_id);
create unique index ux_pay_payroll_doc_regular_period
    on pay_payroll_doc (organization_id, period_id)
    where document_kind = 'REGULAR' and status_id <> 3 and state_id = 1;
