create table pay_payroll_line
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    payroll_doc_id bigint not null references pay_payroll_doc(id) on delete cascade,
    employee_id bigint not null references pay_employee(id),
    employment_id bigint not null references pay_employment(id),
    worked_days numeric(6,2) not null default 0,
    worked_hours numeric(8,2) not null default 0,
    gross_amount numeric(18,2) not null default 0,
    deduction_amount numeric(18,2) not null default 0,
    employer_tax_amount numeric(18,2) not null default 0,
    advance_amount numeric(18,2) not null default 0,
    net_amount numeric(18,2) not null default 0,
    payable_amount numeric(18,2) not null default 0,
    constraint pay_payroll_line_pkey primary key (id),
    constraint ck_pay_payroll_line_time check (worked_days >= 0 and worked_hours >= 0),
    constraint ux_pay_payroll_line_employee unique (payroll_doc_id, employee_id)
);

create index idx_pay_payroll_line_organization_id on pay_payroll_line (organization_id);
create index idx_pay_payroll_line_payroll_doc_id on pay_payroll_line (payroll_doc_id);
create index idx_pay_payroll_line_employee_id on pay_payroll_line (employee_id);
create index idx_pay_payroll_line_employment_id on pay_payroll_line (employment_id);
