create table pay_payroll_calc_line
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    payroll_line_id bigint not null references pay_payroll_line(id) on delete cascade,
    component_id integer not null references pay_component(id),
    base_amount numeric(18,2) not null default 0,
    quantity numeric(12,4),
    rate numeric(9,4),
    amount numeric(18,2) not null,
    is_manual boolean not null default false,
    note varchar(500),
    constraint pay_payroll_calc_line_pkey primary key (id),
    constraint ux_pay_payroll_calc_line_component
        unique (payroll_line_id, component_id)
);

create index idx_pay_payroll_calc_line_organization_id on pay_payroll_calc_line (organization_id);
create index idx_pay_payroll_calc_line_payroll_line_id on pay_payroll_calc_line (payroll_line_id);
create index idx_pay_payroll_calc_line_component_id on pay_payroll_calc_line (component_id);
