create table pay_payment_batch
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    period_id bigint not null references pay_period(id),
    payroll_doc_id bigint references pay_payroll_doc(id),
    doc_number varchar(100) not null,
    doc_date timestamp without time zone not null,
    payment_kind varchar(20) not null,
    source_type varchar(20) not null,
    bank_account_id integer references org_bank_account(id),
    cash_box_id integer references cash_box(id),
    source_chart_account_id integer not null references acc_chart_account(id),
    offset_account_id integer references acc_chart_account(id),
    currency_id smallint not null references cmn_currency(id),
    total_amount numeric(18,2) not null default 0,
    status_id smallint not null references cmn_document_status(id),
    bank_operation_id bigint references bank_operation(id),
    cash_operation_id bigint references cash_operation(id),
    note varchar(1000),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    created_by_user_id integer references sys_user(id),
    posted_at timestamp without time zone,
    posted_by_user_id integer references sys_user(id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer references sys_user(id),
    constraint pay_payment_batch_pkey primary key (id),
    constraint ck_pay_payment_batch_kind
        check (payment_kind in ('ADVANCE', 'FINAL')),
    constraint ck_pay_payment_batch_source
        check (source_type in ('BANK', 'CASH')),
    constraint ck_pay_payment_batch_source_reference check (
        (source_type = 'BANK' and bank_account_id is not null and cash_box_id is null)
        or (source_type = 'CASH' and cash_box_id is not null and bank_account_id is null)
    ),
    constraint ck_pay_payment_batch_operation_reference check (
        not (bank_operation_id is not null and cash_operation_id is not null)
    ),
    constraint ck_pay_payment_batch_amount check (total_amount >= 0),
    constraint ux_pay_payment_batch_org_doc_number unique (organization_id, doc_number)
);

create index idx_pay_payment_batch_organization_id on pay_payment_batch (organization_id);
create index idx_pay_payment_batch_period_id on pay_payment_batch (period_id);
create index idx_pay_payment_batch_payroll_doc_id on pay_payment_batch (payroll_doc_id);
create index idx_pay_payment_batch_status_id on pay_payment_batch (status_id);
create index idx_pay_payment_batch_bank_operation_id on pay_payment_batch (bank_operation_id);
create index idx_pay_payment_batch_cash_operation_id on pay_payment_batch (cash_operation_id);
create unique index ux_pay_payment_batch_bank_operation_id
    on pay_payment_batch (bank_operation_id)
    where bank_operation_id is not null;
create unique index ux_pay_payment_batch_cash_operation_id
    on pay_payment_batch (cash_operation_id)
    where cash_operation_id is not null;
