create table pay_payment_line
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    payment_batch_id bigint not null references pay_payment_batch(id) on delete cascade,
    employee_id bigint not null references pay_employee(id),
    payroll_line_id bigint references pay_payroll_line(id),
    amount numeric(18,2) not null,
    note varchar(500),
    constraint pay_payment_line_pkey primary key (id),
    constraint ck_pay_payment_line_amount check (amount > 0),
    constraint ux_pay_payment_line_employee unique (payment_batch_id, employee_id)
);

create index idx_pay_payment_line_organization_id on pay_payment_line (organization_id);
create index idx_pay_payment_line_payment_batch_id on pay_payment_line (payment_batch_id);
create index idx_pay_payment_line_employee_id on pay_payment_line (employee_id);
create index idx_pay_payment_line_payroll_line_id on pay_payment_line (payroll_line_id);
