create table hr_employee_work_schedule
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    employee_id bigint not null references pay_employee(id),
    name varchar(200) not null,
    effective_from date not null,
    effective_to date,
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    created_by_user_id integer references sys_user(id),
    updated_by_user_id integer references sys_user(id),
    constraint hr_employee_work_schedule_pkey primary key (id),
    constraint ck_hr_employee_work_schedule_dates
        check (effective_to is null or effective_to >= effective_from)
);

create index idx_hr_employee_work_schedule_employee
    on hr_employee_work_schedule (organization_id, employee_id);

create index idx_hr_employee_work_schedule_dates
    on hr_employee_work_schedule (effective_from, effective_to);

create table hr_employee_work_schedule_day
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    schedule_id bigint not null references hr_employee_work_schedule(id) on delete cascade,
    day_of_week smallint not null,
    work_hours numeric(5,2) not null,
    constraint hr_employee_work_schedule_day_pkey primary key (id),
    constraint ux_hr_employee_work_schedule_day unique (schedule_id, day_of_week),
    constraint ck_hr_employee_work_schedule_day_number check (day_of_week between 1 and 7),
    constraint ck_hr_employee_work_schedule_day_hours check (work_hours > 0 and work_hours <= 24)
);

create index idx_hr_employee_work_schedule_day_organization
    on hr_employee_work_schedule_day (organization_id);

create index idx_hr_employee_work_schedule_day_schedule
    on hr_employee_work_schedule_day (schedule_id);
