create table hr_absence_type
(
    id smallint generated by default as identity not null,
    code varchar(50) not null,
    name varchar(200) not null,
    timesheet_category varchar(20) not null,
    is_paid boolean not null default false,
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    constraint hr_absence_type_pkey primary key (id),
    constraint ux_hr_absence_type_code unique (code),
    constraint ck_hr_absence_type_category
        check (timesheet_category in ('LEAVE', 'SICK', 'ABSENT'))
);

insert into hr_absence_type
    (id, code, name, timesheet_category, is_paid, state_id, created_date)
values
    (1, 'ANNUAL_LEAVE', 'Mehnat ta''tili', 'LEAVE', true, 1, now()),
    (2, 'SICK_LEAVE', 'Kasallik varaqasi', 'SICK', true, 1, now()),
    (3, 'UNPAID_LEAVE', 'Ish haqi saqlanmagan ta''til', 'ABSENT', false, 1, now()),
    (4, 'MATERNITY_LEAVE', 'Homiladorlik va tug''ish ta''tili', 'LEAVE', true, 1, now()),
    (5, 'STUDY_LEAVE', 'O''quv ta''tili', 'LEAVE', true, 1, now()),
    (6, 'UNEXCUSED_ABSENCE', 'Sababsiz ishga kelmaslik', 'ABSENT', false, 1, now()),
    (7, 'OTHER_ABSENCE', 'Boshqa yo''qlik', 'ABSENT', false, 1, now())
on conflict (id) do update
set code = excluded.code,
    name = excluded.name,
    timesheet_category = excluded.timesheet_category,
    is_paid = excluded.is_paid,
    state_id = excluded.state_id;

select setval(
    pg_get_serial_sequence('hr_absence_type', 'id'),
    (select max(id) from hr_absence_type));

create table hr_absence
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    employee_id bigint not null references pay_employee(id),
    absence_type_id smallint not null references hr_absence_type(id),
    doc_number varchar(100) not null,
    doc_date date not null,
    start_date date not null,
    end_date date not null,
    note varchar(1000),
    state_id smallint not null default 1 references cmn_state(id),
    created_date timestamp without time zone not null default now(),
    updated_date timestamp without time zone,
    created_by_user_id integer references sys_user(id),
    updated_by_user_id integer references sys_user(id),
    constraint hr_absence_pkey primary key (id),
    constraint ux_hr_absence_org_doc_number unique (organization_id, doc_number),
    constraint ck_hr_absence_dates check (end_date >= start_date)
);

create index idx_hr_absence_employee
    on hr_absence (organization_id, employee_id);

create index idx_hr_absence_dates
    on hr_absence (start_date, end_date);

create index idx_hr_absence_type
    on hr_absence (absence_type_id);

create table hr_absence_attachment
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    absence_id bigint not null references hr_absence(id) on delete cascade,
    file_path varchar(500) not null,
    original_file_name varchar(255) not null,
    content_type varchar(150) not null,
    file_size bigint not null,
    telegram_file_id varchar(300) not null,
    telegram_message_id integer not null,
    created_date timestamp without time zone not null default now(),
    created_by_user_id integer references sys_user(id),
    constraint hr_absence_attachment_pkey primary key (id),
    constraint ck_hr_absence_attachment_size check (file_size > 0)
);

create index idx_hr_absence_attachment_organization
    on hr_absence_attachment (organization_id);

create index idx_hr_absence_attachment_absence
    on hr_absence_attachment (absence_id);
