alter table pay_period
    add column if not exists daily_work_hours numeric(8,4);

do $$
declare
    invalid_periods text;
begin
    select string_agg(id::text, ', ' order by id)
    into invalid_periods
    from pay_period
    where norm_work_days <> trunc(norm_work_days)
       or norm_work_days < 1
       or norm_work_days > extract(day from make_date(period_year, period_month, 1) + interval '1 month - 1 day');

    if invalid_periods is not null then
        raise exception 'Cannot backfill payroll period work dates: invalid norm_work_days for period IDs: %', invalid_periods;
    end if;
end $$;

create table pay_period_work_day
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    period_id bigint not null references pay_period(id) on delete cascade,
    work_date date not null,
    constraint pay_period_work_day_pkey primary key (id),
    constraint ux_pay_period_work_day_period_date unique (period_id, work_date)
);

create index idx_pay_period_work_day_organization_date
    on pay_period_work_day (organization_id, work_date);

update pay_period
set daily_work_hours = round(norm_work_hours / norm_work_days, 4);

with period_days as
(
    select
        period.id as period_id,
        period.organization_id,
        period.norm_work_days::integer as required_work_days,
        calendar_day.work_date::date as work_date,
        case
            when extract(isodow from calendar_day.work_date) between 1 and 5 then 0
            else 1
        end as weekday_priority
    from pay_period period
    cross join lateral generate_series(
        make_date(period.period_year, period.period_month, 1),
        make_date(period.period_year, period.period_month, 1) + interval '1 month - 1 day',
        interval '1 day') as calendar_day(work_date)
), ranked_period_days as
(
    select
        period_id,
        organization_id,
        required_work_days,
        work_date,
        row_number() over (
            partition by period_id
            order by weekday_priority, work_date) as work_day_number
    from period_days
)
insert into pay_period_work_day (organization_id, period_id, work_date)
select organization_id, period_id, work_date
from ranked_period_days
where work_day_number <= required_work_days;

alter table pay_period
    alter column daily_work_hours set not null;

alter table pay_period
    add constraint ck_pay_period_daily_work_hours
        check (daily_work_hours > 0 and daily_work_hours <= 24);

create table pay_timesheet_line_day
(
    id bigint generated by default as identity not null,
    organization_id integer not null references org_organization(id),
    timesheet_line_id bigint not null references pay_timesheet_line(id) on delete cascade,
    work_date date not null,
    source_status_code varchar(50) not null,
    source_absence_id bigint references hr_absence(id),
    source_schedule_id bigint references hr_employee_work_schedule(id),
    source_absence_type_id smallint references hr_absence_type(id),
    status_code varchar(50) not null,
    absence_type_id smallint references hr_absence_type(id),
    timesheet_category varchar(20),
    worked_hours numeric(8,2) not null default 0,
    constraint pay_timesheet_line_day_pkey primary key (id),
    constraint ux_pay_timesheet_line_day_line_date unique (timesheet_line_id, work_date),
    constraint ck_pay_timesheet_line_day_fixed_status_absence_type check (
        status_code not in ('WORKED', 'PLANNED_WORK', 'DAY_OFF', 'NOT_EMPLOYED')
        or absence_type_id is null
    ),
    constraint ck_pay_timesheet_line_day_category check (
        timesheet_category is null or timesheet_category in ('LEAVE', 'SICK', 'ABSENT')
    ),
    constraint ck_pay_timesheet_line_day_worked_hours check (
        (status_code = 'WORKED' and worked_hours >= 1) or
        (status_code <> 'WORKED' and worked_hours = 0)
    )
);

create index idx_pay_timesheet_line_day_organization_date
    on pay_timesheet_line_day (organization_id, work_date);
