begin;

create table if not exists pay_payroll_line_segment
(
    id                    bigint generated by default as identity not null,
    organization_id       integer not null references org_organization(id),
    payroll_line_id       bigint not null references pay_payroll_line(id) on delete cascade,
    employment_id         bigint not null references pay_employment(id),
    segment_start_date    date not null,
    segment_end_date      date not null,
    monthly_salary        numeric(18,2) not null default 0,
    employment_rate       numeric(5,4) not null default 1,
    worked_days           numeric(6,2) not null default 0,
    worked_hours          numeric(8,2) not null default 0,
    norm_work_days        numeric(6,2) not null default 0,
    norm_work_hours       numeric(8,2) not null default 0,
    component_snapshot_json jsonb not null default '[]'::jsonb,
    constraint pay_payroll_line_segment_pkey primary key (id),
    constraint ck_pay_payroll_line_segment_dates check (segment_end_date >= segment_start_date),
    constraint ck_pay_payroll_line_segment_quantities check (
        worked_days >= 0 and worked_hours >= 0 and norm_work_days >= 0 and norm_work_hours >= 0
    ),
    constraint ux_pay_payroll_line_segment_line_start unique (payroll_line_id, segment_start_date)
);

create index if not exists idx_pay_payroll_line_segment_organization_id
    on pay_payroll_line_segment (organization_id);
create index if not exists idx_pay_payroll_line_segment_employment_start
    on pay_payroll_line_segment (employment_id, segment_start_date);

commit;
