begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- Kadr buyrug'i (prikaz). DRAFT holatida yaratiladi; tasdiqlanganda (POSTED)
-- pay_employment intervalini hosil qiladi yoki yopadi (bo'shatish).
create table if not exists pay_hr_order (
    id                   bigint generated by default as identity primary key,
    organization_id      integer     not null,
    order_number         varchar(30) not null,
    order_date           date        not null,
    order_type           varchar(20) not null,
    employee_id          bigint      not null,
    effective_date       date        not null,
    status_id            smallint    not null,
    basis                varchar(500),
    note                 varchar(500),
    department_id        integer,
    position_id          integer,
    employment_type      varchar(30),
    monthly_salary       numeric(18,2),
    employment_rate      numeric(5,4),
    weekly_hours         numeric(6,2),
    currency_id          smallint,
    expense_account_id   integer,
    advance_method       varchar(10),
    advance_value        numeric(18,2),
    employment_id        bigint,
    created_date         timestamp without time zone not null,
    updated_date         timestamp without time zone,
    created_by_user_id   integer,
    updated_by_user_id   integer,
    confirmed_date       timestamp without time zone,
    confirmed_by_user_id integer,
    constraint fk_pay_hr_order_organization  foreign key (organization_id)    references org_organization (id),
    constraint fk_pay_hr_order_employee      foreign key (employee_id)        references pay_employee (id),
    constraint fk_pay_hr_order_department    foreign key (department_id)      references org_department (id),
    constraint fk_pay_hr_order_position      foreign key (position_id)        references org_position (id),
    constraint fk_pay_hr_order_currency      foreign key (currency_id)        references cmn_currency (id),
    constraint fk_pay_hr_order_expense_acc   foreign key (expense_account_id) references acc_chart_account (id),
    constraint fk_pay_hr_order_employment    foreign key (employment_id)      references pay_employment (id),
    constraint fk_pay_hr_order_status        foreign key (status_id)          references cmn_document_status (id),
    constraint ck_pay_hr_order_type          check (order_type in ('HIRE','TRANSFER','PAY_CHANGE','DISMISSAL'))
);

create index if not exists idx_pay_hr_order_organization_id on pay_hr_order (organization_id);
create index if not exists idx_pay_hr_order_employee_id on pay_hr_order (employee_id);
create unique index if not exists uq_pay_hr_order_number on pay_hr_order (organization_id, order_number);

commit;
