create table fa_movement_doc
(
    id bigint generated by default as identity constraint fa_movement_doc_pkey primary key,
    organization_id integer not null constraint fa_movement_doc_organization_id_fkey references org_organization (id),
    state_id smallint not null constraint fa_movement_doc_state_id_fkey references cmn_state (id),
    doc_number character varying(100) not null,
    doc_date timestamp without time zone not null,
    status_id smallint not null constraint fa_movement_doc_status_id_fkey references cmn_document_status (id),
    from_department_id integer constraint fa_movement_doc_from_department_id_fkey references org_department (id),
    to_department_id integer constraint fa_movement_doc_to_department_id_fkey references org_department (id),
    from_responsible_user_id integer constraint fa_movement_doc_from_responsible_user_id_fkey references sys_user (id),
    to_responsible_user_id integer constraint fa_movement_doc_to_responsible_user_id_fkey references sys_user (id),
    note character varying(500),
    created_date timestamp without time zone default now() not null,
    created_by_user_id integer constraint fa_movement_doc_created_by_user_id_fkey references sys_user (id),
    updated_date timestamp without time zone default now() not null,
    updated_by_user_id integer constraint fa_movement_doc_updated_by_user_id_fkey references sys_user (id),
    posted_at timestamp without time zone,
    posted_by_user_id integer constraint fa_movement_doc_posted_by_user_id_fkey references sys_user (id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer constraint fa_movement_doc_cancelled_by_user_id_fkey references sys_user (id),
    constraint ck_fa_movement_doc_target_changed check
    (
        from_department_id is distinct from to_department_id
        or from_responsible_user_id is distinct from to_responsible_user_id
    )
);

create unique index ux_fa_movement_doc_org_doc_number on fa_movement_doc using btree (organization_id, doc_number);
create index idx_fa_movement_doc_state_id on fa_movement_doc using btree (state_id);
create index idx_fa_movement_doc_status_id on fa_movement_doc using btree (status_id);
create index idx_fa_movement_doc_doc_date on fa_movement_doc using btree (doc_date);
create index idx_fa_movement_doc_from_department_id on fa_movement_doc using btree (from_department_id);
create index idx_fa_movement_doc_to_department_id on fa_movement_doc using btree (to_department_id);
create index idx_fa_movement_doc_from_responsible_user_id on fa_movement_doc using btree (from_responsible_user_id);
create index idx_fa_movement_doc_to_responsible_user_id on fa_movement_doc using btree (to_responsible_user_id);
