create table fa_movement_doc_line
(
    id bigint generated by default as identity constraint fa_movement_doc_line_pkey primary key,
    movement_doc_id bigint not null constraint fa_movement_doc_line_movement_doc_id_fkey references fa_movement_doc (id) on delete cascade,
    fa_asset_id bigint not null constraint fa_movement_doc_line_fa_asset_id_fkey references fa_asset (id),
    note character varying(500)
);

create index idx_fa_movement_doc_line_movement_doc_id on fa_movement_doc_line using btree (movement_doc_id);
create index idx_fa_movement_doc_line_fa_asset_id on fa_movement_doc_line using btree (fa_asset_id);
