create table fa_depreciation_run
(
    id bigint generated by default as identity constraint fa_depreciation_run_pkey primary key,
    organization_id integer not null constraint fa_depreciation_run_organization_id_fkey references org_organization (id),
    state_id smallint not null constraint fa_depreciation_run_state_id_fkey references cmn_state (id),
    doc_number character varying(100) not null,
    period_month date not null,
    status_id smallint not null constraint fa_depreciation_run_status_id_fkey references cmn_document_status (id),
    note character varying(500),
    created_date timestamp without time zone default now() not null,
    created_by_user_id integer constraint fa_depreciation_run_created_by_user_id_fkey references sys_user (id),
    updated_date timestamp without time zone default now() not null,
    updated_by_user_id integer constraint fa_depreciation_run_updated_by_user_id_fkey references sys_user (id),
    posted_at timestamp without time zone,
    posted_by_user_id integer constraint fa_depreciation_run_posted_by_user_id_fkey references sys_user (id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer constraint fa_depreciation_run_cancelled_by_user_id_fkey references sys_user (id),
    constraint ck_fa_depreciation_run_period_month_start check (period_month = date_trunc('month', period_month)::date)
);

create unique index ux_fa_depreciation_run_org_doc_number on fa_depreciation_run using btree (organization_id, doc_number);
create unique index ux_fa_depreciation_run_org_period_active on fa_depreciation_run using btree (organization_id, period_month) where (status_id <> 3);
create index idx_fa_depreciation_run_state_id on fa_depreciation_run using btree (state_id);
create index idx_fa_depreciation_run_status_id on fa_depreciation_run using btree (status_id);
create index idx_fa_depreciation_run_period_month on fa_depreciation_run using btree (period_month);
