create table fa_depreciation_run_line
(
    id bigint generated by default as identity constraint fa_depreciation_run_line_pkey primary key,
    depreciation_run_id bigint not null constraint fa_depreciation_run_line_depreciation_run_id_fkey references fa_depreciation_run (id) on delete cascade,
    fa_asset_id bigint not null constraint fa_depreciation_run_line_fa_asset_id_fkey references fa_asset (id),
    amount numeric(18,2) not null,
    note character varying(500),
    constraint ck_fa_depreciation_run_line_amount_positive check (amount > 0)
);

create unique index ux_fa_depreciation_run_line_run_asset on fa_depreciation_run_line using btree (depreciation_run_id, fa_asset_id);
create index idx_fa_depreciation_run_line_run_id on fa_depreciation_run_line using btree (depreciation_run_id);
create index idx_fa_depreciation_run_line_fa_asset_id on fa_depreciation_run_line using btree (fa_asset_id);
