create table fa_disposal_doc_line
(
    id bigint generated by default as identity constraint fa_disposal_doc_line_pkey primary key,
    disposal_doc_id bigint not null constraint fa_disposal_doc_line_disposal_doc_id_fkey references fa_disposal_doc (id) on delete cascade,
    fa_asset_id bigint not null constraint fa_disposal_doc_line_fa_asset_id_fkey references fa_asset (id),
    book_value numeric(18,2) not null default 0,
    sale_amount numeric(18,2) not null default 0,
    gain_loss numeric(18,2) not null default 0,
    note character varying(500),
    constraint ck_fa_disposal_doc_line_book_value_nonnegative check (book_value >= 0),
    constraint ck_fa_disposal_doc_line_sale_amount_nonnegative check (sale_amount >= 0)
);

create unique index ux_fa_disposal_doc_line_doc_asset on fa_disposal_doc_line using btree (disposal_doc_id, fa_asset_id);
create index idx_fa_disposal_doc_line_doc_id on fa_disposal_doc_line using btree (disposal_doc_id);
create index idx_fa_disposal_doc_line_fa_asset_id on fa_disposal_doc_line using btree (fa_asset_id);
