create table fa_revaluation_doc
(
    id bigint generated by default as identity constraint fa_revaluation_doc_pkey primary key,
    organization_id integer not null constraint fa_revaluation_doc_organization_id_fkey references org_organization (id),
    state_id smallint not null constraint fa_revaluation_doc_state_id_fkey references cmn_state (id),
    doc_number character varying(100) not null,
    revaluation_date timestamp without time zone not null,
    status_id smallint not null constraint fa_revaluation_doc_status_id_fkey references cmn_document_status (id),
    reason character varying(500),
    created_date timestamp without time zone default now() not null,
    created_by_user_id integer constraint fa_revaluation_doc_created_by_user_id_fkey references sys_user (id),
    updated_date timestamp without time zone default now() not null,
    updated_by_user_id integer constraint fa_revaluation_doc_updated_by_user_id_fkey references sys_user (id),
    posted_at timestamp without time zone,
    posted_by_user_id integer constraint fa_revaluation_doc_posted_by_user_id_fkey references sys_user (id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer constraint fa_revaluation_doc_cancelled_by_user_id_fkey references sys_user (id)
);

create unique index ux_fa_revaluation_doc_org_doc_number on fa_revaluation_doc using btree (organization_id, doc_number);
create index idx_fa_revaluation_doc_state_id on fa_revaluation_doc using btree (state_id);
create index idx_fa_revaluation_doc_status_id on fa_revaluation_doc using btree (status_id);
create index idx_fa_revaluation_doc_date on fa_revaluation_doc using btree (revaluation_date);
