create table fa_revaluation_doc_line
(
    id bigint generated by default as identity constraint fa_revaluation_doc_line_pkey primary key,
    revaluation_doc_id bigint not null constraint fa_revaluation_doc_line_revaluation_doc_id_fkey references fa_revaluation_doc (id) on delete cascade,
    fa_asset_id bigint not null constraint fa_revaluation_doc_line_fa_asset_id_fkey references fa_asset (id),
    old_value numeric(18,2) not null,
    new_value numeric(18,2) not null,
    revaluation_amount numeric(18,2) not null,
    note character varying(500),
    constraint ck_fa_revaluation_doc_line_old_value_nonnegative check (old_value >= 0),
    constraint ck_fa_revaluation_doc_line_new_value_nonnegative check (new_value >= 0)
);

create unique index ux_fa_revaluation_doc_line_doc_asset on fa_revaluation_doc_line using btree (revaluation_doc_id, fa_asset_id);
create index idx_fa_revaluation_doc_line_doc_id on fa_revaluation_doc_line using btree (revaluation_doc_id);
create index idx_fa_revaluation_doc_line_fa_asset_id on fa_revaluation_doc_line using btree (fa_asset_id);
