begin;

create table fa_commissioning_doc
(
    id bigint generated by default as identity not null,
    organization_id integer not null
        constraint fa_commissioning_doc_organization_id_fkey references org_organization (id),
    state_id smallint not null
        constraint fa_commissioning_doc_state_id_fkey references cmn_state (id),
    doc_number varchar(50) not null,
    doc_date timestamp without time zone not null,
    status_id smallint not null
        constraint fa_commissioning_doc_status_id_fkey references cmn_document_status (id),
    note varchar(500),
    created_date timestamp without time zone default now() not null,
    created_by_user_id integer
        constraint fa_commissioning_doc_created_by_user_id_fkey references sys_user (id),
    updated_date timestamp without time zone default now() not null,
    updated_by_user_id integer
        constraint fa_commissioning_doc_updated_by_user_id_fkey references sys_user (id),
    posted_at timestamp without time zone,
    posted_by_user_id integer
        constraint fa_commissioning_doc_posted_by_user_id_fkey references sys_user (id),
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer
        constraint fa_commissioning_doc_cancelled_by_user_id_fkey references sys_user (id),
    constraint pk_fa_commissioning_doc primary key (id),
    constraint uq_fa_commissioning_doc_org_number unique (organization_id, doc_number)
);

create index ix_fa_commissioning_doc_org_date
    on fa_commissioning_doc (organization_id, doc_date);

create index ix_fa_commissioning_doc_status_id
    on fa_commissioning_doc (status_id);

commit;
