begin;

create table fa_commissioning_doc_line
(
    id bigint generated by default as identity not null,
    commissioning_doc_id bigint not null
        constraint fa_commissioning_doc_line_commissioning_doc_id_fkey references fa_commissioning_doc (id),
    fa_asset_id bigint not null
        constraint fa_commissioning_doc_line_fa_asset_id_fkey references fa_asset (id),
    capitalized_amount numeric(24,8) not null,
    depr_start_date timestamp without time zone not null,
    salvage_value numeric(24,8) default 0 not null,
    useful_life_months integer not null,
    depreciation_method_id smallint not null
        constraint fa_commissioning_doc_line_depreciation_method_id_fkey references cmn_fa_depreciation_method (id),
    planned_units_total numeric(24,8),
    department_id integer
        constraint fa_commissioning_doc_line_department_id_fkey references org_department (id),
    responsible_user_id integer
        constraint fa_commissioning_doc_line_responsible_user_id_fkey references sys_user (id),
    capital_investment_account_id integer not null
        constraint fa_commissioning_doc_line_capital_investment_account_id_fkey references acc_chart_account (id),
    accumulated_depreciation_account_id integer not null
        constraint fa_commissioning_doc_line_accumulated_depreciation_account_id_fkey references acc_chart_account (id),
    depreciation_expense_account_id integer not null
        constraint fa_commissioning_doc_line_depreciation_expense_account_id_fkey references acc_chart_account (id),
    note varchar(500),
    constraint pk_fa_commissioning_doc_line primary key (id),
    constraint uq_fa_commissioning_doc_line_asset unique (commissioning_doc_id, fa_asset_id),
    constraint ck_fa_commissioning_doc_line_capitalized_amount check (capitalized_amount >= 0),
    constraint ck_fa_commissioning_doc_line_salvage_value check
    (
        salvage_value >= 0 and salvage_value <= capitalized_amount
    ),
    constraint ck_fa_commissioning_doc_line_useful_life check (useful_life_months > 0),
    constraint ck_fa_commissioning_doc_line_planned_units check
    (
        planned_units_total is null or planned_units_total > 0
    )
);

create index ix_fa_commissioning_doc_line_commissioning_doc_id
    on fa_commissioning_doc_line (commissioning_doc_id);

create index ix_fa_commissioning_doc_line_fa_asset_id
    on fa_commissioning_doc_line (fa_asset_id);

create index ix_fa_commissioning_doc_line_department_id
    on fa_commissioning_doc_line (department_id);

create index ix_fa_commissioning_doc_line_responsible_user_id
    on fa_commissioning_doc_line (responsible_user_id);

create index ix_fa_commissioning_doc_line_depreciation_method_id
    on fa_commissioning_doc_line (depreciation_method_id);

create index ix_fa_commissioning_doc_line_capital_investment_account_id
    on fa_commissioning_doc_line (capital_investment_account_id);

create index ix_fa_commissioning_doc_line_accumulated_depreciation_account_id
    on fa_commissioning_doc_line (accumulated_depreciation_account_id);

create index ix_fa_commissioning_doc_line_depreciation_expense_account_id
    on fa_commissioning_doc_line (depreciation_expense_account_id);

commit;
