create table cash_box (
    id integer generated by default as identity not null,
    organization_id integer not null,
    branch_id integer,
    code character varying(50) not null,
    name character varying(250) not null,
    currency_id smallint not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    is_main boolean default false not null,
    responsible_user_id integer,
    opening_balance numeric(18,2) default 0 not null,
    opening_balance_date date,
    constraint cash_box_pkey primary key (id),
    constraint cash_box_branch_id_fkey foreign key (branch_id) references org_branch(id),
    constraint cash_box_currency_id_fkey foreign key (currency_id) references cmn_currency(id),
    constraint cash_box_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint cash_box_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_cash_box_branch_id on cash_box using btree (branch_id);
create index idx_cash_box_currency_id on cash_box using btree (currency_id);
create unique index idx_cash_box_org_code on cash_box using btree (organization_id, code);
create index idx_cash_box_organization_id on cash_box using btree (organization_id);
create index idx_cash_box_state_id on cash_box using btree (state_id);
create index idx_cash_box_is_main on cash_box using btree (is_main);
create index idx_cash_box_responsible_user_id on cash_box using btree (responsible_user_id);
