-- direction_id is relative to fiscal_cash_register_id:
--   -1 (OUT): fiscal cash register -> cash box
--    1 (IN):  cash box -> fiscal cash register
create table cash_fiscal_transfer_doc
(
    id                          bigint generated by default as identity not null,
    organization_id             integer not null,
    doc_number                  character varying(100) not null,
    doc_date                    timestamp without time zone not null,
    fiscal_cash_register_id     integer not null,
    cash_box_id                 integer not null,
    direction_id               smallint not null,
    currency_id                smallint not null,
    amount                     numeric(18, 2) not null,
    exchange_rate              numeric(18, 6) default 1 not null,
    fiscal_cash_account_id      integer,
    cash_box_account_id         integer,
    status_id                  smallint default 1 not null,
    state_id                   smallint default 1 not null,
    comment                    character varying(1000),
    created_date               timestamp without time zone default now() not null,
    posted_at                  timestamp without time zone,
    posted_by_user_id          integer,
    cancelled_at               timestamp without time zone,
    cancelled_by_user_id       integer,

    constraint cash_fiscal_transfer_doc_pkey
        primary key (id),

    constraint cash_fiscal_transfer_doc_organization_id_fkey
        foreign key (organization_id) references org_organization(id),

    constraint cash_fiscal_transfer_doc_fiscal_cash_register_id_fkey
        foreign key (fiscal_cash_register_id) references fiscal_cash_register(id),

    constraint cash_fiscal_transfer_doc_cash_box_id_fkey
        foreign key (cash_box_id) references cash_box(id),

    constraint cash_fiscal_transfer_doc_direction_id_fkey
        foreign key (direction_id) references cmn_movement_direction(id),

    constraint cash_fiscal_transfer_doc_currency_id_fkey
        foreign key (currency_id) references cmn_currency(id),

    constraint cash_fiscal_transfer_doc_fiscal_cash_account_id_fkey
        foreign key (fiscal_cash_account_id) references acc_chart_account(id),

    constraint cash_fiscal_transfer_doc_cash_box_account_id_fkey
        foreign key (cash_box_account_id) references acc_chart_account(id),

    constraint cash_fiscal_transfer_doc_status_id_fkey
        foreign key (status_id) references cmn_document_status(id),

    constraint cash_fiscal_transfer_doc_state_id_fkey
        foreign key (state_id) references cmn_state(id),

    constraint cash_fiscal_transfer_doc_posted_by_user_id_fkey
        foreign key (posted_by_user_id) references sys_user(id),

    constraint cash_fiscal_transfer_doc_cancelled_by_user_id_fkey
        foreign key (cancelled_by_user_id) references sys_user(id),

    constraint ck_cash_fiscal_transfer_doc_number_not_empty
        check (btrim(doc_number) <> ''),

    constraint ck_cash_fiscal_transfer_doc_direction
        check (direction_id in (-1, 1)),

    constraint ck_cash_fiscal_transfer_doc_amount
        check (amount > 0),

    constraint ck_cash_fiscal_transfer_doc_exchange_rate
        check (exchange_rate > 0),

    constraint ck_cash_fiscal_transfer_doc_accounts
        check
        (
            status_id = 1
            or
            (
                fiscal_cash_account_id is not null
                and cash_box_account_id is not null
                and fiscal_cash_account_id <> cash_box_account_id
            )
        ),

    constraint ck_cash_fiscal_transfer_doc_status
        check (status_id in (1, 2, 3)),

    constraint ck_cash_fiscal_transfer_doc_lifecycle
        check
        (
            (
                status_id = 1
                and posted_at is null
                and posted_by_user_id is null
                and cancelled_at is null
                and cancelled_by_user_id is null
            )
            or
            (
                status_id = 2
                and posted_at is not null
                and posted_by_user_id is not null
                and cancelled_at is null
                and cancelled_by_user_id is null
            )
            or
            (
                status_id = 3
                and posted_at is not null
                and posted_by_user_id is not null
                and cancelled_at is not null
                and cancelled_by_user_id is not null
            )
        )
);

create index idx_cash_fiscal_transfer_doc_organization_id
    on cash_fiscal_transfer_doc using btree (organization_id);

create index idx_cash_fiscal_transfer_doc_fiscal_cash_register_id
    on cash_fiscal_transfer_doc using btree (fiscal_cash_register_id);

create index idx_cash_fiscal_transfer_doc_cash_box_id
    on cash_fiscal_transfer_doc using btree (cash_box_id);

create index idx_cash_fiscal_transfer_doc_direction_id
    on cash_fiscal_transfer_doc using btree (direction_id);

create index idx_cash_fiscal_transfer_doc_currency_id
    on cash_fiscal_transfer_doc using btree (currency_id);

create index idx_cash_fiscal_transfer_doc_status_id
    on cash_fiscal_transfer_doc using btree (status_id);

create index idx_cash_fiscal_transfer_doc_state_id
    on cash_fiscal_transfer_doc using btree (state_id);

create index idx_cash_fiscal_transfer_doc_doc_date
    on cash_fiscal_transfer_doc using btree (doc_date);

create index idx_cash_fiscal_transfer_doc_org_doc_date
    on cash_fiscal_transfer_doc using btree (organization_id, doc_date);

create index idx_cash_fiscal_transfer_doc_fiscal_cash_account_id
    on cash_fiscal_transfer_doc using btree (fiscal_cash_account_id);

create index idx_cash_fiscal_transfer_doc_cash_box_account_id
    on cash_fiscal_transfer_doc using btree (cash_box_account_id);

create index idx_cash_fiscal_transfer_doc_posted_by_user_id
    on cash_fiscal_transfer_doc using btree (posted_by_user_id);

create index idx_cash_fiscal_transfer_doc_cancelled_by_user_id
    on cash_fiscal_transfer_doc using btree (cancelled_by_user_id);
