-- Table: public.sale_condition

CREATE TABLE public.sale_condition (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    organization_id integer NOT NULL,
    costing_method_id smallint NOT NULL,
    vat_rate_id smallint NOT NULL,
    start_date timestamp without time zone DEFAULT now() NOT NULL,
    end_date timestamp without time zone,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_sale_condition_dates CHECK (((end_date IS NULL) OR (end_date >= start_date))),
    CONSTRAINT sale_condition_pkey PRIMARY KEY (id),
    CONSTRAINT sale_condition_costing_method_id_fkey FOREIGN KEY (costing_method_id) REFERENCES public.cmn_costing_method(id),
    CONSTRAINT sale_condition_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id),
    CONSTRAINT sale_condition_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id),
    CONSTRAINT sale_condition_vat_rate_id_fkey FOREIGN KEY (vat_rate_id) REFERENCES public.cmn_vat_rate(id)
);

insert into public.sale_condition (id, organization_id, costing_method_id, vat_rate_id, start_date, end_date, state_id, created_date) values
    ('1', '8', '1', '2', '2026-04-01 00:00:00', '2026-12-31 23:59:59.999999', '1', '2026-06-27 16:03:42.262514'),
    ('2', '8', '3', '4', '2026-06-15 17:02:00', NULL, '1', '2026-06-27 17:04:40.566346'),
    ('3', '8', '1', '2', '2026-06-29 14:50:40', NULL, '2', '2026-06-29 16:09:34.054396'),
    ('4', '8', '1', '2', '2026-06-25 16:09:00', NULL, '1', '2026-06-29 16:10:04.471712');

CREATE INDEX idx_sale_condition_costing_method_id ON public.sale_condition USING btree (costing_method_id);

CREATE INDEX idx_sale_condition_dates ON public.sale_condition USING btree (start_date, end_date);

CREATE INDEX idx_sale_condition_org_state_dates ON public.sale_condition USING btree (organization_id, state_id, start_date, end_date);

CREATE INDEX idx_sale_condition_organization_id ON public.sale_condition USING btree (organization_id);

CREATE INDEX idx_sale_condition_state_id ON public.sale_condition USING btree (state_id);

CREATE INDEX idx_sale_condition_vat_rate_id ON public.sale_condition USING btree (vat_rate_id);
