create table sale_doc 
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    doc_number character varying(100) not null,
    doc_date timestamp without time zone not null,
    counterparty_id integer not null,
    warehouse_id integer not null,
    currency_id smallint not null,
    total_amount numeric(24,8) default 0 not null,
    vat_amount numeric(24,8) default 0 not null,
    final_amount numeric(24,8) default 0 not null,
    status_id smallint not null,
    comment character varying(1000),
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    contract_id bigint,
    exchange_rate numeric(18,6) default 1 not null,
    posted_at timestamp without time zone,
    posted_by_user_id integer,
    cancelled_at timestamp without time zone,
    cancelled_by_user_id integer,
    customer_account_id integer,
    vat_account_id integer,
    constraint sale_doc_pkey primary key (id),
    constraint sale_doc_contract_id_fkey foreign key (contract_id) references cmn_contract(id),
    constraint sale_doc_counterparty_id_fkey foreign key (counterparty_id) references counterparty_card(id),
    constraint sale_doc_currency_id_fkey foreign key (currency_id) references cmn_currency(id),
    constraint sale_doc_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint sale_doc_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint sale_doc_status_id_fkey foreign key (status_id) references cmn_document_status(id),
    constraint sale_doc_warehouse_id_fkey foreign key (warehouse_id) references inv_warehouse(id),
    constraint sale_doc_customer_account_id_fkey foreign key (customer_account_id) references acc_chart_account(id),
    constraint sale_doc_vat_account_id_fkey foreign key (vat_account_id) references acc_chart_account(id)
);

create index idx_sale_doc_contract_id on sale_doc using btree (contract_id) WHERE (contract_id IS not null);
create index idx_sale_doc_counterparty_id on sale_doc using btree (counterparty_id);
create index idx_sale_doc_doc_date on sale_doc using btree (doc_date);
create index idx_sale_doc_organization_id on sale_doc using btree (organization_id);
create index idx_sale_doc_state_id on sale_doc using btree (state_id);
create index idx_sale_doc_status_id on sale_doc using btree (status_id);
create index idx_sale_doc_warehouse_id on sale_doc using btree (warehouse_id);
create index idx_sale_doc_posted_by_user_id on sale_doc using btree (posted_by_user_id);
create index idx_sale_doc_cancelled_by_user_id on sale_doc using btree (cancelled_by_user_id);
create index idx_sale_doc_customer_account_id on sale_doc (customer_account_id);
create index idx_sale_doc_vat_account_id on sale_doc (vat_account_id);

set default_tablespace = '';

set default_table_access_method = heap;

insert into sale_doc (id, organization_id, doc_number, doc_date, counterparty_id, warehouse_id, currency_id, total_amount, vat_amount, final_amount, status_id, comment, state_id, created_date, contract_id) values
    ('78', '8', '100000076', '2026-06-29 16:42:30.843443', '18', '7', '1', '18975.00000000', '2277.00000000', '21252.00000000', '4', null, '1', '2026-06-29 16:42:30.843443', '9'),
    ('79', '8', '100000077', '2026-06-29 17:21:54.01643', '18', '7', '1', '65296.00000000', '7835.52000000', '73131.52000000', '1', 'FIFO bo''yicha sotilyapti', '2', '2026-06-29 17:21:54.01643', '9'),
    ('80', '8', '100000078', '2026-06-29 17:36:29.055026', '18', '7', '1', '65296.00000000', '7835.52000000', '73131.52000000', '1', null, '1', '2026-06-29 17:36:29.055026', '10');
