--Toshkent shahri
insert into ref_district (short_name, full_name, state_id, region_id)
(SELECT N'Бектемирский', N'Бектемирский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Мирзо Улугбекский', N'Мирзо Улугбекский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Мирабадский', N'Мирабадский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Алмазорский', N'Алмазорский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Сергелийский', N'Сергелийский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Учтепинский', N'Учтепинский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Яшнабадский', N'Яшнабадский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Чиланзарский', N'Чиланзарский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Шайхантахурский', N'Шайхантахурский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Юнусабадский', N'Юнусабадский',1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL		  
(SELECT N'Яккасарайский', N'Яккасарайский', 1,id FROM info_region where full_name = N'Город Ташкент' limit 1) UNION ALL
--Toshkent viloyati
(SELECT N'Бостанлыкский', N'Бостанлыкский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Аккурганский', N'Аккурганский', 1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Ахангаранский', N'Ахангаранский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Бекабадский', N'Бекабадский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Букинский', N'Букинский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Зангиатинский', N'Зангиатинский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Кибрайский', N'Кибрайский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Куйичирчикский', N'Куйичирчикский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Паркентский', N'Паркентский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Пскентский', N'Пскентский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Ташкентский', N'Ташкентский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Уртачирчикский', N'Уртачирчикский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Чиназский', N'Чиназский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Юкарычирчикский', N'Юкарычирчикский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'Янгиюльский', N'Янгиюльский',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Алмалык', N'г. Алмалык',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Ангрен', N'г. Ангрен',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Ахангаран', N'г. Ахангаран',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Бекабад', N'г. Бекабад',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Чирчик', N'г. Чирчик',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Янгиюль', N'г. Янгиюль',1,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
(SELECT N'г. Нурафшан', N'г. Нурафшан',2,id FROM info_region where full_name = N'Ташкентская' limit 1) UNION ALL
--Andijon viloyati
(SELECT N'г. Андижан', N'г. Андижан',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'г. Асака', N'г. Асака',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Алтынкульский', N'Алтынкульский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Андижанский', N'Андижанский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Асакинский', N'Асакинский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Балыкчинский', N'Балыкчинский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Бозский', N'Бозский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Булакбашинский', N'Булакбашинский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Джалалкудукский', N'Джалалкудукский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Избасканкий', N'Избасканкий',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Кургантепинский', N'Кургантепинский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Мархаматский', N'Мархаматский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Пахтаабадский', N'Пахтаабадский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Улугнорский', N'Улугнорский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Ходжаабадский', N'Ходжаабадский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'г. Ханабад', N'г. Ханабад',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
(SELECT N'Шахриханский', N'Шахриханский',1,id FROM info_region where full_name = N'Андижанская' limit 1) UNION ALL
--Buxoro viloyati
(SELECT N'г. Бухара', N'г. Бухара', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'г. Каган', N'г. Каган', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Алатский', N'Алатский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Бухарский', N'Бухарский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Вабкентский', N'Вабкентский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Гиждуванский', N'Гиждуванский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Жандарский', N'Жандарский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Каганский', N'Каганский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Каракульский', N'Каракульский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Пешкунский', N'Пешкунский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Ромитанский', N'Ромитанский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Караулбазарский', N'Караулбазарский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
(SELECT N'Шафирканский', N'Шафирканский', 1,id FROM info_region where full_name = N'Бухарская' limit 1) UNION ALL
--Jizzax viloyati
(SELECT N'Арнасайский', N'Арнасайский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Янгиабадский', N'Янгиабадский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Бахмалький', N'Бахмалький', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Галлааральский', N'Галлааральский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Дусткликский', N'Дусткликский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Пахтакорский', N'Пахтакорский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Зааминский', N'Зааминский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Джизакский', N'Джизакский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Зарбдарский', N'Зарбдарский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Зафарабадский', N'Зафарабадский', 1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Мирзачульский', N'Мирзачульский',1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'Фаришский', N'Фаришский',1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
(SELECT N'г. Джизак', N'г. Джизак',1,id FROM info_region where full_name = N'Джизакская' limit 1) UNION ALL
--Qoraqalpog'iston Respublikasi
(SELECT N'Амударьинский', N'Амударьинский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Берунийский', N'Берунийский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Канлыкульский', N'Канлыкульский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Караузякский', N'Караузякский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Кегелийский', N'Кегелийский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Кунградский', N'Кунградский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Муйнакский', N'Муйнакский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Нукусский', N'Нукусский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Тахтакупырский', N'Тахтакупырский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Турткульский', N'Турткульский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Хаджейлийский', N'Хаджейлийский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Чимбайский', N'Чимбайский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Шуманайский', N'Шуманайский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'Элликкалинский', N'Элликкалинский', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'г. Нукус', N'г. Нукус', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'г. Тахиаташ', N'г. Тахиаташ', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL
(SELECT N'"Бозатау', N'Бозатау', 1,id FROM info_region where full_name = N'Республика Каракалпакстан' limit 1) UNION ALL

--Qashqadaryo viloyati
(SELECT N'Гузарский', N'Гузарский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Дехканабадский', N'Дехканабадский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Камашинский', N'Камашинский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Каршинский', N'Каршинский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Касанский', N'Касанский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Касбинский', N'Касбинский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Китабский', N'Китабский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Миришкорский', N'Миришкорский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Мубарекский', N'Мубарекский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Нишанский', N'Нишанский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Чиракчинский', N'Чиракчинский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Шахризабский', N'Шахризабский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'Яккабагский', N'Яккабагский', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'г. Карши', N'г. Карши', 1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL
(SELECT N'г. Шахрисабз', N'г. Шахрисабз',1,id FROM info_region where full_name = N'Кашкадарьинская' limit 1) UNION ALL

--Navoiy viloyati
(SELECT N'Канимехский', N'Канимехский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Кызылтепинский', N'Кызылтепинский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Навбахорский', N'Навбахорский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Карманинский', N'Карманинский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Нуратинский', N'Нуратинский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Тамдынский', N'Тамдынский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Учкудукский', N'Учкудукский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'Хатырчинский', N'Хатырчинский', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'г. Зарафшан', N'г. Зарафшан', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
(SELECT N'г. Навои', N'г. Навои', 1,id FROM info_region where full_name = N'Навоийская' limit 1) UNION ALL
--Namangan viloyati
(SELECT N'Касансайский', N'Касансайский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Мингбулакский', N'Мингбулакский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Наманганский', N'Наманганский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Нарынский', N'Нарынский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Папский', N'Папский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Туракурганский', N'Туракурганский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Уйчинский', N'Уйчинский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Учкурганский', N'Учкурганский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Чартакский', N'Чартакский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Чустский', N'Чустский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'Янгикурганский', N'Янгикурганский', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
(SELECT N'г. Наманган', N'г. Наманган', 1,id FROM info_region where full_name = N'Наманганская' limit 1) UNION ALL
--Samarqand viloyati
(SELECT N'Акдарьинский', N'Акдарьинский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Булунгурский', N'Булунгурский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Джамбайский', N'Джамбайский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Иштыханский', N'Иштыханский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Каттакурганский', N'Каттакурганский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Кошрабадский', N'Кошрабадский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Нарпайский', N'Нарпайский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Нурабадский', N'Нурабадский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Пайарыкский', N'Пайарыкский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Пастдаргомский', N'Пастдаргомский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Пахтачийский', N'Пахтачийский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Самаркандский', N'Самаркандский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Тайлакский', N'Тайлакский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'Ургутский', N'Ургутский', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'г. Каттакурган', N'г. Каттакурган', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
(SELECT N'г. Самарканд', N'г. Самарканд', 1,id FROM info_region where full_name = N'Самаркандская' limit 1) UNION ALL
-- Surxandaryo viloyati
(SELECT N'Алтынсайский', N'Алтынсайский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Ангорский', N'Ангорский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Байсунский', N'Байсунский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Бандиханский', N'Бандиханский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Денауский', N'Денауский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Джаркурганский', N'Джаркурганский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Кумкурганский', N'Кумкурганский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Кызырыкский', N'Кызырыкский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Музрабадский', N'Музрабадский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Сариасийский', N'Сариасийский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Термезский', N'Термезский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Узунский', N'Узунский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Шерабадский', N'Шерабадский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'Шурчинский', N'Шурчинский', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
(SELECT N'г. Термез', N'г. Термез', 1,id FROM info_region where full_name = N'Сурхандарьинская' limit 1) UNION ALL
-- Sirdaryo viloyati
(SELECT N'Акалтинский', N'Акалтинский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Баяутский', N'Баяутский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Гулистанский', N'Гулистанский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Мирзаабадский', N'Мирзаабадский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Сардоба', N'Сардоба', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Сайхунабадский', N'Сайхунабадский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Сырдарьинский', N'Сырдарьинский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'Хавастский', N'Хавастский', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'г. Гулистан', N'г. Гулистан', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'г. Ширин', N'г. Ширин', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
(SELECT N'г. Янгиер', N'г. Янгиер', 1,id FROM info_region where full_name = N'Сырдарьинская' limit 1) UNION ALL
--Farg'ona viloyati
(SELECT N'Алтыарыкский', N'Алтыарыкский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Куштепа', N'Куштепа', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Багдадский', N'Багдадский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Бешарыкский', N'Бешарыкский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Бувайдийский', N'Бувайдийский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Дангаринский', N'Дангаринский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Кувинский', N'Кувинский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Риштанский', N'Риштанский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Сохский', N'Сохский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Ташлакский', N'Ташлакский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Узбекистанский', N'Узбекистанский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Учкуприкский', N'Учкуприкский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Ферганский', N'Ферганский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Фуркатский', N'Фуркатский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'Язвинский', N'Язвинский', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'г. Коканд', N'г. Коканд', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'г. Кувасай', N'г. Кувасай', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'г. Маргилан', N'г. Маргилан', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
(SELECT N'г. Фергана', N'г. Фергана', 1,id FROM info_region where full_name = N'Ферганская' limit 1) UNION ALL
--Xorazm viloyati
(SELECT N'Багатский', N'Багатский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Гурленский', N'Гурленский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Кошкупырский', N'Кошкупырский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Ургенчский', N'Ургенчский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Хазараспский', N'Хазараспский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Ханкинский', N'Ханкинский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Хивинский', N'Хивинский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Шаватский', N'Шаватский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Янгиарыкский', N'Янгиарыкский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Янгибазарский', N'Янгибазарский', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'Ургенч', N'Ургенч', 1,id FROM info_region where full_name = N'Хорезмская' limit 1) UNION ALL
(SELECT N'г. Хива', N'г. Хива', 1,id FROM info_region where full_name = N'Хорезмская' limit 1);
