create table counterparty_didox_profile
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    counterparty_id integer not null,
    vat_reg_code character varying(100) not null,
    vat_reg_status_code smallint not null,
    legal_address character varying(1000) not null,
    effective_from date not null,
    effective_to date,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint ck_counterparty_didox_profile_dates check ((effective_to is null) or (effective_to >= effective_from)),
    constraint counterparty_didox_profile_pkey primary key (id),
    constraint counterparty_didox_profile_counterparty_id_fkey foreign key (counterparty_id) references counterparty_card(id),
    constraint counterparty_didox_profile_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint counterparty_didox_profile_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint counterparty_didox_profile_vat_reg_status_code_fkey foreign key (vat_reg_status_code) references cmn_didox_vat_reg_status(code)
);

create index idx_counterparty_didox_profile_counterparty_id on counterparty_didox_profile using btree (counterparty_id);
create index idx_counterparty_didox_profile_effective_dates on counterparty_didox_profile using btree (effective_from, effective_to);
create index idx_counterparty_didox_profile_organization_id on counterparty_didox_profile using btree (organization_id);
create index idx_counterparty_didox_profile_state_id on counterparty_didox_profile using btree (state_id);
create index idx_counterparty_didox_profile_vat_reg_status_code on counterparty_didox_profile using btree (vat_reg_status_code);
create unique index ux_counterparty_didox_profile_counterparty_effective_from on counterparty_didox_profile using btree (counterparty_id, effective_from);
