<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\DejaVuSans.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Acc\OpeningBalances\Queries\" />
    <Folder Include="Features\Acc\OpeningBalances\Validators\" />
    <Folder Include="Features\Inv\OpeningInventories\Services\" />
    <Folder Include="Features\Inv\OpeningInventories\Filters\" />
    <Folder Include="Features\Inv\OpeningInventories\Errors\" />
    <Folder Include="Features\Inv\OpeningInventories\Queries\" />
    <Folder Include="Features\Inv\OpeningInventories\Validators\" />
    <Folder Include="Features\Inv\OpeningInventories\Projections\" />
    <Folder Include="Features\Register\PostingEngines\Resolvers\" />
  </ItemGroup>

</Project>
