create table cmn_region 
(
    id integer generated by default as identity not null,
    code varchar(10) not null,
    short_name character varying(250) not null,
    full_name character varying(250) not null,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint cmn_region_pkey primary key (id),
    constraint cmn_region_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create unique index uidx_cmn_region_code on cmn_region using btree (code);

insert into cmn_region (id, code, short_name, full_name, state_id, created_date) values
    ('1', '26', 'Toshkent shahri', 'Toshkent shahri', '1', '2026-06-05 16:36:13.009757'),
    ('2', '27', 'Toshkent', 'Toshkent', '1', '2026-06-05 16:36:13.009757'),
    ('3', '3', 'Andijon', 'Andijon', '1', '2026-06-05 16:36:13.009757'),
    ('4', '6', 'Buxoro', 'Buxoro', '1', '2026-06-05 16:36:13.009757'),
    ('5', '8', 'Jizzax', 'Jizzax', '1', '2026-06-05 16:36:13.009757'),
    ('6', '35', 'Qoraqalpog‘iston Respublikasi', 'Qoraqalpog‘iston Respublikasi', '1', '2026-06-05 16:36:13.009757'),
    ('7', '10', 'Qashqadaryo', 'Qashqadaryo', '1', '2026-06-05 16:36:13.009757'),
    ('8', '12', 'Navoiy', 'Navoiy', '1', '2026-06-05 16:36:13.009757'),
    ('9', '14', 'Namangan', 'Namangan', '1', '2026-06-05 16:36:13.009757'),
    ('10', '18', 'Samarqand', 'Samarqand', '1', '2026-06-05 16:36:13.009757'),
    ('11', '22', 'Surxondaryo', 'Surxondaryo', '1', '2026-06-05 16:36:13.009757'),
    ('12', '24', 'Sirdaryo', 'Sirdaryo', '1', '2026-06-05 16:36:13.009757'),
    ('13', '30', 'Farg‘ona', 'Farg‘ona', '1', '2026-06-05 16:36:13.009757'),
    ('14', '33', 'Xorazm', 'Xorazm', '1', '2026-06-05 16:36:13.009757');

