-- Table: public.cmn_currency

CREATE TABLE public.cmn_currency (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    code character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    symbol character varying(10),
    state_id smallint NOT NULL,
    CONSTRAINT cmn_currency_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_currency_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_currency (id, code, name, symbol, state_id) values
    ('1', 'UZS', 'Uzbek so''m', 'so''m', '1'),
    ('2', 'USD', 'US Dollar', '$', '1'),
    ('3', 'RUB', 'Russian Ruble', '₽', '1'),
    ('4', 'EUR', 'Euro', '€', '1');

CREATE UNIQUE INDEX idx_cmn_currency_code ON public.cmn_currency USING btree (code);
