-- Table: public.cmn_unit

CREATE TABLE public.cmn_unit (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 6)  NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    state_id smallint NOT NULL,
    CONSTRAINT cmn_unit_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_unit_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_unit (id, code, name, state_id) values
    ('1', 'dona', 'Dona', '1'),
    ('2', 'kg', 'Kilogram', '1'),
    ('3', 'litr', 'Litr', '1'),
    ('4', 'metr', 'Metr', '1'),
    ('5', 'xizmat', 'Xizmat', '1');

CREATE UNIQUE INDEX idx_cmn_unit_code ON public.cmn_unit USING btree (code);
