insert into cmn_district (short_name, full_name, state_id, region_id)
-- Toshkent shahri
(select N'Bektemir', N'Bektemir', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Mirzo Ulug‘bek', N'Mirzo Ulug‘bek', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Mirobod', N'Mirobod', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Olmazor', N'Olmazor', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Sergeli', N'Sergeli', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Uchtepa', N'Uchtepa', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Yashnobod', N'Yashnobod', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Chilonzor', N'Chilonzor', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Shayxontohur', N'Shayxontohur', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Yunusobod', N'Yunusobod', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
(select N'Yakkasaroy', N'Yakkasaroy', 1, id from cmn_region where full_name = N'Toshkent shahri' limit 1) union all
-- Toshkent viloyati
(select N'Bo‘stonliq', N'Bo‘stonliq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Oqqo‘rg‘on', N'Oqqo‘rg‘on',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Ohangaron', N'Ohangaron',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Bekobod', N'Bekobod',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Bo‘ka', N'Bo‘ka',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Zangiota', N'Zangiota',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Qibray', N'Qibray',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Quyichirchiq', N'Quyichirchiq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Parkent', N'Parkent',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Piskent', N'Piskent',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Toshkent', N'Toshkent',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'O‘rtachirchiq', N'O‘rtachirchiq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Chinoz', N'Chinoz',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Yuqorichirchiq', N'Yuqorichirchiq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Yangiyo‘l', N'Yangiyo‘l',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Olmaliq', N'Olmaliq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Angren', N'Angren',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Chirchiq', N'Chirchiq',1,id from cmn_region where full_name = N'Toshkent' limit 1) union all
(select N'Nurafshon', N'Nurafshon',2,id from cmn_region where full_name = N'Toshkent' limit 1) union all
-- Andijon viloyati
(select N'Andijon', N'Andijon',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Asaka', N'Asaka',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Oltinko‘l', N'Oltinko‘l',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Baliqchi', N'Baliqchi',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Bo‘z', N'Bo‘z',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Buloqboshi', N'Buloqboshi',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Jalolquduq', N'Jalolquduq',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Izboskan', N'Izboskan',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Qo‘rg‘ontepa', N'Qo‘rg‘ontepa',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Marhamat', N'Marhamat',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Paxtaobod', N'Paxtaobod',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Ulug‘nor', N'Ulug‘nor',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Xo‘jaobod', N'Xo‘jaobod',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Xonobod', N'Xonobod',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
(select N'Shahrixon', N'Shahrixon',1,id from cmn_region where full_name = N'Andijon' limit 1) union all
-- Buxoro viloyati
(select N'Buxoro', N'Buxoro', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Kogon', N'Kogon', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Olot', N'Olot', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Vobkent', N'Vobkent', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'G‘ijduvon', N'G‘ijduvon', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Jondor', N'Jondor', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Qorako‘l', N'Qorako‘l', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Peshku', N'Peshku', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Romitan', N'Romitan', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Qorovulbozor', N'Qorovulbozor', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
(select N'Shofirkon', N'Shofirkon', 1,id from cmn_region where full_name = N'Buxoro' limit 1) union all
-- Jizzax viloyati
(select N'Arnasoy', N'Arnasoy', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Yangiobod', N'Yangiobod', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Baxmal', N'Baxmal', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'G‘allaorol', N'G‘allaorol', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Do‘stlik', N'Do‘stlik', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Paxtakor', N'Paxtakor', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Zomin', N'Zomin', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Jizzax', N'Jizzax', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Zarbdor', N'Zarbdor', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Zafarobod', N'Zafarobod', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Mirzacho‘l', N'Mirzacho‘l', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
(select N'Forish', N'Forish', 1,id from cmn_region where full_name = N'Jizzax' limit 1) union all
-- Qoraqalpog'iston Respublikasi
(select N'Amudaryo', N'Amudaryo', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Beruniy', N'Beruniy', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Qanliko‘l', N'Qanliko‘l', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Qorao‘zak', N'Qorao‘zak', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Kegeyli', N'Kegeyli', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Qo‘ng‘irot', N'Qo‘ng‘irot', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Mo‘ynoq', N'Mo‘ynoq', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Nuqus', N'Nuqus', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Taxtako‘pir', N'Taxtako‘pir', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'To‘rtko‘l', N'To‘rtko‘l', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Xo‘jayli', N'Xo‘jayli', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Chimboy', N'Chimboy', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Shumanay', N'Shumanay', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Ellikqal’a', N'Ellikqal’a', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Taxiatosh', N'Taxiatosh', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
(select N'Bo‘zatov', N'Bo‘zatov', 1,id from cmn_region where full_name = N'Qoraqalpog‘iston Respublikasi' limit 1) union all
-- Qashqadaryo viloyati
(select N'G‘uzor', N'G‘uzor', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Dehqonobod', N'Dehqonobod', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Qamashi', N'Qamashi', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Qarshi', N'Qarshi', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Koson', N'Koson', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Kasbi', N'Kasbi', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Kitob', N'Kitob', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Mirishkor', N'Mirishkor', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Muborak', N'Muborak', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Nishon', N'Nishon', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Chiroqchi', N'Chiroqchi', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Shahrisabz', N'Shahrisabz', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
(select N'Yakkabog‘', N'Yakkabog‘', 1,id from cmn_region where full_name = N'Qashqadaryo' limit 1) union all
-- Navoiy viloyati
(select N'Konimex', N'Konimex', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Qiziltepa', N'Qiziltepa', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Navbahor', N'Navbahor', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Karmana', N'Karmana', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Nurata', N'Nurata', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Tomdi', N'Tomdi', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Uchquduq', N'Uchquduq', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Xatirchi', N'Xatirchi', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Zarafshon', N'Zarafshon', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
(select N'Navoiy', N'Navoiy', 1,id from cmn_region where full_name = N'Navoiy' limit 1) union all
-- Namangan viloyati
(select N'Kosonsoy', N'Kosonsoy', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Mingbuloq', N'Mingbuloq', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Namangan', N'Namangan', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Naryn', N'Naryn', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Pop', N'Pop', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Turakurgan', N'Turakurgan', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Uychi', N'Uychi', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Uchkurgan', N'Uchkurgan', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Chartak', N'Chartak', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Chust', N'Chust', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
(select N'Yangiqo‘rg‘on', N'Yangiqo‘rg‘on', 1,id from cmn_region where full_name = N'Namangan' limit 1) union all
-- Samarqand viloyati
(select N'Ishtixon', N'Ishtixon', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Bulung‘ur', N'Bulung‘ur', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Jomboy', N'Jomboy', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Kattaqo‘rg‘on', N'Kattaqo‘rg‘on', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Qo‘shrabot', N'Qo‘shrabot', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Narpay', N'Narpay', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Nurobod', N'Nurobod', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Payariq', N'Payariq', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Pastdarg‘om', N'Pastdarg‘om', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Paxtachi', N'Paxtachi', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Samarqand', N'Samarqand', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Toyloq', N'Toyloq', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
(select N'Urgut', N'Urgut', 1,id from cmn_region where full_name = N'Samarqand' limit 1) union all
-- Surxondaryo viloyati
(select N'Oltinsoy', N'Oltinsoy', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Angor', N'Angor', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Boysun', N'Boysun', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Bandixon', N'Bandixon', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Denov', N'Denov', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Jarqo‘rg‘on', N'Jarqo‘rg‘on', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Qumqo‘rg‘on', N'Qumqo‘rg‘on', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Qiziriq', N'Qiziriq', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Muzrabot', N'Muzrabot', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Sariosiyo', N'Sariosiyo', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Termiz', N'Termiz', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Sherobod', N'Sherobod', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
(select N'Sho‘rchi', N'Sho‘rchi', 1,id from cmn_region where full_name = N'Surxondaryo' limit 1) union all
-- Sirdaryo viloyati
(select N'Oqoltin', N'Oqoltin', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Bayaut', N'Bayaut', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Guliston', N'Guliston', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Mirzaobod', N'Mirzaobod', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Sardoba', N'Sardoba', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Sayxunobod', N'Sayxunobod', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Sirdaryo', N'Sirdaryo', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Xovos', N'Xovos', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Shirin', N'Shirin', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
(select N'Yangiyer', N'Yangiyer', 1,id from cmn_region where full_name = N'Sirdaryo' limit 1) union all
-- Farg'ona viloyati
(select N'Oltariq', N'Oltariq', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Qo‘shtepa', N'Qo‘shtepa', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Bag‘dod', N'Bag‘dod', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Beshariq', N'Beshariq', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Buvayda', N'Buvayda', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Dang‘ara', N'Dang‘ara', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Quva', N'Quva', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Rishton', N'Rishton', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Soh', N'Soh', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Toshloq', N'Toshloq', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'O‘zbekiston', N'O‘zbekiston', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Uchko‘prik', N'Uchko‘prik', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Farg‘ona', N'Farg‘ona', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Furqat', N'Furqat', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Yozyovon', N'Yozyovon', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Qo‘qon', N'Qo‘qon', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Quvasoy', N'Quvasoy', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
(select N'Marg‘ilon', N'Marg‘ilon', 1,id from cmn_region where full_name = N'Farg‘ona' limit 1) union all
-- Xorazm viloyati
(select N'Bog‘ot', N'Bog‘ot', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Gurlan', N'Gurlan', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Qo‘shko‘pir', N'Qo‘shko‘pir', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Urgench', N'Urgench', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Xazorasp', N'Xazorasp', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Xonqa', N'Xonqa', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Xiva', N'Xiva', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Shovot', N'Shovot', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Yangiariq', N'Yangiariq', 1,id from cmn_region where full_name = N'Xorazm' limit 1) union all
(select N'Yangibozor', N'Yangibozor', 1,id from cmn_region where full_name = N'Xorazm' limit 1);