-- Table: public.cmn_document_status

CREATE TABLE public.cmn_document_status (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    state_id smallint NOT NULL,
    CONSTRAINT cmn_document_status_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_document_status_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_document_status (id, code, name, state_id) values
    ('1', 'draft', 'Qoralama', '1'),
    ('2', 'posted', 'O''tkazilgan', '1'),
    ('3', 'cancelled', 'Bekor qilingan', '1'),
    ('4', 'pending', 'Kutilmoqda', '1');

CREATE UNIQUE INDEX idx_cmn_document_status_code ON public.cmn_document_status USING btree (code);
