-- Table: public.cmn_counterparty_type

CREATE TABLE public.cmn_counterparty_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 4)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    state_id smallint NOT NULL,
    CONSTRAINT cmn_counterparty_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_counterparty_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_counterparty_type (id, code, name, state_id) values
    ('1', 'client', 'Mijoz', '1'),
    ('2', 'supplier', 'Yetkazib beruvchi', '1'),
    ('3', 'client_supplier', 'Mijoz va yetkazib beruvchi', '1');

CREATE UNIQUE INDEX idx_cmn_counterparty_type_code ON public.cmn_counterparty_type USING btree (code);
