-- Table: public.cmn_payment_type

CREATE TABLE public.cmn_payment_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    state_id smallint NOT NULL,
    CONSTRAINT cmn_payment_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_payment_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_payment_type (id, code, name, state_id) values
    ('1', 'cash', 'Naqd', '1'),
    ('2', 'bank', 'Bank', '1'),
    ('3', 'card', 'Karta', '1'),
    ('4', 'transfer', 'O''tkazma', '1');

CREATE UNIQUE INDEX idx_cmn_payment_type_code ON public.cmn_payment_type USING btree (code);
