create table cmn_bank 
(
    id integer generated by default as identity not null,
    code character varying(50) not null,
    name character varying(250) not null,
    legal_name character varying(500),
    license_number character varying(50),
    license_date date,
    address character varying(500),
    opened_date date,
    source_updated_date date,
    inn character varying(20),
    mfo character varying(20),
    website character varying(250),
    latitude numeric(9,6),
    longitude numeric(9,6),
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint cmn_bank_pkey primary key (id),
    constraint cmn_bank_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint ck_cmn_bank_latitude check (latitude is null or latitude between -90 and 90),
    constraint ck_cmn_bank_longitude check (longitude is null or longitude between -180 and 180)
);

create unique index idx_cmn_bank_code on cmn_bank using btree (code);
create index idx_cmn_bank_state_id on cmn_bank using btree (state_id);
create index idx_cmn_bank_inn on cmn_bank using btree (inn);
create index idx_cmn_bank_license_number on cmn_bank using btree (license_number);
