-- Table: public.cmn_bank

CREATE TABLE public.cmn_bank (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 7)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(250) NOT NULL,
    inn character varying(20),
    mfo character varying(20),
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cmn_bank_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_bank_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_bank (id, code, name, mfo, state_id, created_date) values
    ('3', 'KAPITAL', 'Kapitalbank', NULL, '1', '2026-06-06 16:39:53.224198'),
    ('4', 'HAMKOR', 'Hamkorbank', NULL, '1', '2026-06-06 16:39:53.224198'),
    ('5', 'CODEX191315', 'Codex Test Bank Updated', '99998', '1', '2026-06-24 19:13:15.478874'),
    ('2', 'IPOTEKA', 'Ipoteka bank', NULL, '1', '2026-06-06 16:39:53.224198'),
    ('1', 'NBU', 'Milliy bank', NULL, '1', '2026-06-06 16:39:53.224198'),
    ('6', 'Agro', 'AgroBank', '1234', '1', '2026-06-25 13:53:41.945698');

CREATE UNIQUE INDEX idx_cmn_bank_code ON public.cmn_bank USING btree (code);

CREATE INDEX idx_cmn_bank_state_id ON public.cmn_bank USING btree (state_id);
