-- Table: public.cmn_document_type

CREATE TABLE public.cmn_document_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 7)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cmn_document_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_document_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_document_type (id, code, name, state_id, created_date) values
    ('1', 'purchase', 'Xarid / Kirim', '1', '2026-06-06 16:40:07.223429'),
    ('2', 'sale', 'Sotuv', '1', '2026-06-06 16:40:07.223429'),
    ('3', 'bank_operation', 'Bank operatsiyasi', '1', '2026-06-06 16:40:07.223429'),
    ('4', 'cash_operation', 'Kassa operatsiyasi', '1', '2026-06-06 16:40:07.223429'),
    ('5', 'salary', 'Ish haqi', '1', '2026-06-06 16:40:07.223429'),
    ('6', 'expense', 'Xarajat', '1', '2026-06-06 16:40:07.223429');

CREATE UNIQUE INDEX idx_cmn_document_type_code ON public.cmn_document_type USING btree (code);

CREATE INDEX idx_cmn_document_type_state_id ON public.cmn_document_type USING btree (state_id);
