-- Table: public.cmn_operation_type

CREATE TABLE public.cmn_operation_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 6)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cmn_operation_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_operation_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_operation_type (id, code, name, state_id, created_date) values
    ('1', 'in', 'Kirim', '1', '2026-06-06 16:40:19.40134'),
    ('2', 'out', 'Chiqim', '1', '2026-06-06 16:40:19.40134'),
    ('3', 'transfer', 'O''tkazma', '1', '2026-06-06 16:40:19.40134'),
    ('4', 'debt_increase', 'Qarz oshishi', '1', '2026-06-06 16:40:19.40134'),
    ('5', 'debt_decrease', 'Qarz kamayishi', '1', '2026-06-06 16:40:19.40134');

CREATE UNIQUE INDEX idx_cmn_operation_type_code ON public.cmn_operation_type USING btree (code);

CREATE INDEX idx_cmn_operation_type_state_id ON public.cmn_operation_type USING btree (state_id);
