-- Table: public.cmn_tax_type

CREATE TABLE public.cmn_tax_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 3)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cmn_tax_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_tax_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_tax_type (id, code, name, state_id, created_date) values
    ('1', 'none', 'Soliqsiz', '1', '2026-06-06 16:40:32.193179'),
    ('2', 'vat', 'QQS', '1', '2026-06-06 16:40:32.193179');

CREATE UNIQUE INDEX idx_cmn_tax_type_code ON public.cmn_tax_type USING btree (code);

CREATE INDEX idx_cmn_tax_type_state_id ON public.cmn_tax_type USING btree (state_id);
