-- Table: public.cmn_vat_rate

CREATE TABLE public.cmn_vat_rate (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    rate numeric(5,2) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    effective_from date,
    effective_to date,
    CONSTRAINT cmn_vat_rate_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_vat_rate_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id),
    CONSTRAINT cmn_vat_rate_effective_dates_check CHECK (((effective_to IS NULL) OR (effective_from IS NULL) OR (effective_to >= effective_from)))
);

insert into public.cmn_vat_rate (id, code, name, rate, state_id, created_date) values
    ('1', 'vat_0', 'QQS 0%', '0.00', '1', '2026-06-06 16:40:45.727928'),
    ('2', 'vat_12', 'QQS 12%', '12.00', '1', '2026-06-06 16:40:45.727928'),
    ('3', 'vat_15', 'QQS 15%', '15.00', '1', '2026-06-06 16:40:45.727928'),
    ('4', 'vat_6', 'QQS 6%', '6.00', '1', '2026-06-27 13:53:02.619573');

CREATE UNIQUE INDEX idx_cmn_vat_rate_code ON public.cmn_vat_rate USING btree (code);

CREATE INDEX idx_cmn_vat_rate_state_id ON public.cmn_vat_rate USING btree (state_id);

CREATE INDEX idx_cmn_vat_rate_effective_dates ON public.cmn_vat_rate USING btree (effective_from, effective_to);
