-- Table: public.cmn_contract_type

CREATE TABLE public.cmn_contract_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 3)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    state_id smallint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT cmn_contract_type_pkey PRIMARY KEY (id),
    CONSTRAINT cmn_contract_type_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id)
);

insert into public.cmn_contract_type (id, code, name, state_id, created_date) values
    ('1', 'supplier', 'Yetkazib beruvchi bilan shartnoma', '1', '2026-06-17 17:35:47.346557'),
    ('2', 'customer', 'Xaridor bilan shartnoma', '1', '2026-06-17 17:35:47.346557');

CREATE UNIQUE INDEX idx_cmn_contract_type_code ON public.cmn_contract_type USING btree (code);

CREATE INDEX idx_cmn_contract_type_state_id ON public.cmn_contract_type USING btree (state_id);
