-- Table: public.cmn_price_rounding_method

CREATE TABLE public.cmn_price_rounding_method (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT cmn_price_rounding_method_code_key UNIQUE (code),
    CONSTRAINT cmn_price_rounding_method_pkey PRIMARY KEY (id)
);

insert into public.cmn_price_rounding_method (id, code, name) values
    ('1', 'NONE', 'O''zgartirmasdan'),
    ('2', 'UP', 'Yuqoriga yaxlitlash'),
    ('3', 'DOWN', 'Pastga yaxlitlash'),
    ('4', 'NEAREST', 'Eng yaqin qiymatga yaxlitlash');
