create table cmn_pricing_condition 
(
    id bigint generated by default as identity not null,
    organization_id integer not null,
    pricing_method_id smallint not null,
    pricing_value numeric(18,2) not null,
    rounding_method_id smallint not null,
    rounding_precision numeric(12,2) default 1 not null,
    start_date timestamp without time zone default now() not null,
    end_date timestamp without time zone,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint ck_cmn_pricing_condition_dates CHECK (((end_date IS null) OR (end_date >= start_date))),
    constraint ck_cmn_pricing_condition_pricing_value CHECK ((pricing_value >= (0)::numeric)),
    constraint ck_cmn_pricing_condition_rounding_precision CHECK ((rounding_precision > (0)::numeric)),
    constraint cmn_pricing_condition_pkey primary key (id),
    constraint cmn_pricing_condition_organization_id_fkey foreign key (organization_id) references org_organization(id),
    constraint cmn_pricing_condition_pricing_method_id_fkey foreign key (pricing_method_id) references cmn_pricing_method(id),
    constraint cmn_pricing_condition_rounding_method_id_fkey foreign key (rounding_method_id) references cmn_price_rounding_method(id),
    constraint cmn_pricing_condition_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_cmn_pricing_condition_dates on cmn_pricing_condition using btree (start_date, end_date);
create index idx_cmn_pricing_condition_organization_id on cmn_pricing_condition using btree (organization_id);
create index idx_cmn_pricing_condition_pricing_method_id on cmn_pricing_condition using btree (pricing_method_id);
create index idx_cmn_pricing_condition_rounding_method_id on cmn_pricing_condition using btree (rounding_method_id);

insert into cmn_pricing_condition (id, organization_id, pricing_method_id, pricing_value, rounding_method_id, rounding_precision, start_date, end_date, state_id, created_date) values
    ('1', '8', '1', '10.00', '4', '100000.00', '2026-06-27 16:26:44', null, '2', '2026-06-27 16:29:09.970103'),
    ('8', '8', '1', '10.00', '4', '1.00', '2026-06-01 00:00:00', null, '1', '2026-06-29 15:47:45.47747');
