-- Table: public.cmn_costing_method

CREATE TABLE public.cmn_costing_method (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 4)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT cmn_costing_method_code_key UNIQUE (code),
    CONSTRAINT cmn_costing_method_pkey PRIMARY KEY (id)
);

insert into public.cmn_costing_method (id, code, name) values
    ('1', 'FIFO', 'FIFO - birinchi kirgan birinchi chiqadi'),
    ('2', 'LIFO', 'LIFO - oxirgi kirgan birinchi chiqadi'),
    ('3', 'AVERAGE', 'O''rtacha tannarx');
