-- Table: public.cmn_product_price_type

CREATE TABLE public.cmn_product_price_type (
    id smallint GENERATED BY DEFAULT AS IDENTITY (START WITH 3)  NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    CONSTRAINT cmn_product_price_type_code_key UNIQUE (code),
    CONSTRAINT cmn_product_price_type_pkey PRIMARY KEY (id)
);

insert into public.cmn_product_price_type (id, code, name) values
    ('1', 'AVERAGE_COST_PRICE', 'Hisoblangan o''rtacha tannarx'),
    ('2', 'FIXED_SALE_PRICE', 'Belgilangan sotuv narxi');
