-- Table: public.cmn_document_sequence

CREATE TABLE public.cmn_document_sequence (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    document_type_id smallint NOT NULL,
    prefix character varying(50),
    suffix character varying(50),
    current_number bigint DEFAULT 0 NOT NULL,
    padding smallint DEFAULT 5 NOT NULL,
    year smallint,
    month smallint,
    reset_period character varying(20) DEFAULT 'yearly'::character varying NOT NULL,
    state_id smallint DEFAULT 1 NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.cmn_document_sequence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cmn_document_sequence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.cmn_document_sequence_id_seq', 1, false);

ALTER TABLE ONLY public.cmn_document_sequence
    ADD CONSTRAINT cmn_document_sequence_pkey PRIMARY KEY (id);

CREATE INDEX idx_cmn_document_sequence_document_type_id ON public.cmn_document_sequence USING btree (document_type_id);

CREATE INDEX idx_cmn_document_sequence_state_id ON public.cmn_document_sequence USING btree (state_id);

CREATE UNIQUE INDEX uidx_cmn_document_sequence_scope ON public.cmn_document_sequence USING btree (organization_id, document_type_id, COALESCE((year)::integer, 0), COALESCE((month)::integer, 0));

ALTER TABLE ONLY public.cmn_document_sequence
    ADD CONSTRAINT cmn_document_sequence_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES public.cmn_document_type(id);

ALTER TABLE ONLY public.cmn_document_sequence
    ADD CONSTRAINT cmn_document_sequence_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.org_organization(id);

ALTER TABLE ONLY public.cmn_document_sequence
    ADD CONSTRAINT cmn_document_sequence_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.cmn_state(id);
