create table cmn_mxik_catalog
(
    id bigint generated by default as identity not null,
    mxik_code character varying(17) not null,
    name character varying(500) not null,
    source_name character varying(100) not null,
    source_updated_at timestamp without time zone,
    effective_from date not null,
    effective_to date,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint ck_cmn_mxik_catalog_dates check ((effective_to is null) or (effective_to >= effective_from)),
    constraint cmn_mxik_catalog_pkey primary key (id),
    constraint cmn_mxik_catalog_state_id_fkey foreign key (state_id) references cmn_state(id)
);

create index idx_cmn_mxik_catalog_effective_dates on cmn_mxik_catalog using btree (effective_from, effective_to);
create index idx_cmn_mxik_catalog_mxik_code on cmn_mxik_catalog using btree (mxik_code);
create index idx_cmn_mxik_catalog_state_id on cmn_mxik_catalog using btree (state_id);
create unique index ux_cmn_mxik_catalog_code_effective_from on cmn_mxik_catalog using btree (mxik_code, effective_from);
