create table cmn_unit_didox_package
(
    id bigint generated by default as identity not null,
    unit_id smallint not null,
    package_code character varying(50) not null,
    package_name character varying(250) not null,
    effective_from date not null,
    effective_to date,
    state_id smallint not null,
    created_date timestamp without time zone default now() not null,
    constraint ck_cmn_unit_didox_package_dates check ((effective_to is null) or (effective_to >= effective_from)),
    constraint cmn_unit_didox_package_pkey primary key (id),
    constraint cmn_unit_didox_package_state_id_fkey foreign key (state_id) references cmn_state(id),
    constraint cmn_unit_didox_package_unit_id_fkey foreign key (unit_id) references cmn_unit(id)
);

create index idx_cmn_unit_didox_package_effective_dates on cmn_unit_didox_package using btree (effective_from, effective_to);
create index idx_cmn_unit_didox_package_state_id on cmn_unit_didox_package using btree (state_id);
create index idx_cmn_unit_didox_package_unit_id on cmn_unit_didox_package using btree (unit_id);
create unique index ux_cmn_unit_didox_package_unit_effective_from on cmn_unit_didox_package using btree (unit_id, effective_from);
